Repository duckduckgo/Android, pull requests merged in 2022-11, with the labels that each got.

#2475 Fix crash caused by unitialised dispatcher provider
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/DeviceShieldTileService.kt
Labels: QA-Optional

#2460 Trigger translations for autofill: updating username
  app-tracking-protection/vpn-impl/src/main/res/values-cs/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-ro/strings-vpn.xml
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Labels: QA-Optional

#2487 Feature/cristian/privacy dashboard/search bar UI feedback
  app/src/main/java/com/duckduckgo/app/browser/omnibar/animations/TrackersLottieAssetDelegate.kt
  app/src/main/res/drawable/network_logo_chartbeat.xml
  app/src/main/res/drawable/network_logo_google_ads.xml
  app/src/main/res/drawable/network_logo_google_analytics.xml
  app/src/main/res/drawable/network_logo_instagram.xml
  app/src/main/res/drawable/network_logo_mixpanel_inc.xml
  app/src/main/res/drawable/network_logo_outbrain.xml
  app/src/main/res/drawable/network_logo_yahoo_japan_corporation.xml
  app/src/main/res/drawable/network_logo_yandex_llc.xml
  app/src/main/res/drawable/network_logo_youtube.xml
  app/src/main/res/layout/include_omnibar_toolbar.xml
  app/src/main/res/raw/light_trackers.json
  app/src/main/res/raw/light_trackers_1.json
  app/src/main/res/raw/light_trackers_2.json
  app/src/main/res/raw/protected_shield.json
  app/src/main/res/raw/unprotected_shield.json
Labels: QA-Optional

#2492 Add missing instructions to translations
  app-tracking-protection/vpn-impl/src/main/res/values-bg/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-cs/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-da/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-de/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-el/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-es/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-et/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-fi/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-fr/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-hr/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-hu/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-it/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-lt/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-lv/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-nb/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-nl/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-pl/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-pt/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-ro/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-ru/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-sk/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-sl/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-sv/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-tr/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
Labels: QA-Optional

#2420 Add lint custom rules for strings
  app-tracking-protection/vpn-impl/src/main/res/values-bg/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-cs/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-da/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-de/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-el/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-es/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-et/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-fi/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-fr/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-hr/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-hu/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-it/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-lt/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-lv/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-nb/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-nl/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-pl/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-pt/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-ro/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-ru/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-sk/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-sl/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-sv/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-tr/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
  gradle/android-library.gradle
  lint-rules/src/main/java/com/duckduckgo/lint/registry/DuckDuckGoIssueRegistry.kt
  lint-rules/src/main/java/com/duckduckgo/lint/strings/MissingInstructionDetector.kt
  lint-rules/src/main/java/com/duckduckgo/lint/strings/MissingSmartlingRequiredDirectivesDetector.kt
  lint-rules/src/main/java/com/duckduckgo/lint/strings/PlaceholderDetector.kt
  lint-rules/src/test/java/com/duckduckgo/lint/strings/MissingInstructionDetectorTest.kt
  lint-rules/src/test/java/com/duckduckgo/lint/strings/MissingSmartlingRequiredDirectivesDetectorTest.kt
  lint-rules/src/test/java/com/duckduckgo/lint/strings/PlaceholderDetectorTest.kt
Labels: QA-Optional

#2509 Remove site permissions pixels
  app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
  app/src/main/java/com/duckduckgo/app/sitepermissions/SitePermissionsViewModel.kt
  app/src/main/java/com/duckduckgo/app/sitepermissions/permissionsperwebsite/PermissionsPerWebsiteViewModel.kt
  app/src/test/java/com/duckduckgo/app/sitepermissions/PermissionsPerWebsiteViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/sitepermissions/SitePermissionsViewModelTest.kt
  site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsDialogActivityLauncher.kt
  site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/pixels/SitePermissionsPixel.kt
Labels: QA-Optional

#2515 Remove device capability pixel sender
  app/src/test/java/com/duckduckgo/autofill/pixel/AutofillUniquePixelSenderTest.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/pixel/AutofillDeviceCapabilityReporter.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/pixel/AutofillPixelNames.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/pixel/AutofillPixelSender.kt
Labels: QA-Optional

#2511 Wrap ActivityCompat.shouldShowRequestPermissionRationale
  voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/PermissionRationale.kt
  voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/PermissionRequest.kt
  voice-search/voice-search-impl/src/test/java/com/duckduckgo/voice/impl/MicrophonePermissionRequestTest.kt
Labels: QA-Optional

#2520 Autofill defaults to off generally, but overridden to on for internal testers
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/di/AutofillModule.kt
  autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/AutofillPrefsStore.kt
Labels: QA-Optional

#2519 ADS: Bottom Sheet Specs
  common-ui/src/main/res/layout/bottom_sheet_action.xml
  common-ui/src/main/res/layout/bottom_sheet_promo.xml
  common-ui/src/main/res/values/widgets.xml
Labels: STACKED PR - DO NOT MERGE

#2521 ADS: List Items specs
  common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/component/ComponentViewHolder.kt
  common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/listitem/OneLineListItem.kt
  common-ui/src/main/res/layout/component_one_line_item.xml
  common-ui/src/main/res/layout/view_one_line_list_item.xml
  common-ui/src/main/res/layout/view_two_line_item.xml
  common-ui/src/main/res/values/design-system-dimensions.xml
Labels: STACKED PR - DO NOT MERGE

#2517 Remove clear data pixel
  app/src/androidTest/java/com/duckduckgo/app/global/view/ClearPersonalDataActionTest.kt
  app/src/main/java/com/duckduckgo/app/di/PrivacyModule.kt
  app/src/main/java/com/duckduckgo/app/fire/ClearDataPixel.kt
  app/src/main/java/com/duckduckgo/app/global/view/ClearPersonalDataAction.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/test/java/com/duckduckgo/app/fire/ClearDataPixelTest.kt
Labels: QA-Optional

#2533 Remove Site Permissions change when toggle off permission
  app/src/main/java/com/duckduckgo/app/sitepermissions/permissionsperwebsite/PermissionsPerWebsiteViewModel.kt
  app/src/test/java/com/duckduckgo/app/sitepermissions/PermissionsPerWebsiteViewModelTest.kt
Labels: QA-Optional

#2524 Add fingerprint protection random seed
  app/src/androidTest/java/com/duckduckgo/espresso/privacy/FingerprintProtectionTest.kt
  content-scope-scripts/content-scope-scripts-impl/build.gradle
  content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScripts.kt
  content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScriptsTest.kt
  fingerprint-protection/fingerprint-protection-api/src/main/java/com/duckduckgo/fingerprintprotection/api/FingerprintProtectionManager.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/FingerprintProtectionSeedManager.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/FingerprintProtectionSeedWorker.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/di/FingerprintProtectionModule.kt
  fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/FingerprintProtectionSeedWorkerSchedulerTest.kt
  fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/FingerprintProtectionSeedWorkerTest.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/FingerprintProtectionDatabase.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/FingerprintProtectionEntities.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/seed/FingerprintProtectionSeedDao.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/seed/FingerprintProtectionSeedRepository.kt
  fingerprint-protection/fingerprint-protection-store/src/test/java/com/duckduckgo/fingerprintprotection/store/seed/RealFingerprintProtectionSeedRepositoryTest.kt
Labels: STACKED PR - DO NOT MERGE

#2523 Add fingerprint protection module
  app/build.gradle
  app/src/androidTest/java/com/duckduckgo/espresso/privacy/FingerprintProtectionTest.kt
  content-scope-scripts/content-scope-scripts-impl/build.gradle
  content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScripts.kt
  content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScriptsTest.kt
  fingerprint-protection/fingerprint-protection-api/.gitignore
  fingerprint-protection/fingerprint-protection-api/build.gradle
  fingerprint-protection/fingerprint-protection-api/src/main/java/com/duckduckgo/fingerprintprotection/api/FingerprintProtectionFeatureName.kt
  fingerprint-protection/fingerprint-protection-api/src/main/java/com/duckduckgo/fingerprintprotection/api/FingerprintProtectionManager.kt
  fingerprint-protection/fingerprint-protection-impl/.gitignore
  fingerprint-protection/fingerprint-protection-impl/build.gradle
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/FingerprintProtectionFeatureNameUtil.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/FingerprintProtectionSeedManager.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/FingerprintProtectionSeedWorker.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/di/FingerprintProtectionModule.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingbattery/FingerprintingBatteryContentScopeConfigPlugin.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingbattery/FingerprintingBatteryFeaturePlugin.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingcanvas/FingerprintingCanvasContentScopeConfigPlugin.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingcanvas/FingerprintingCanvasFeaturePlugin.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintinghardware/FingerprintingHardwareContentScopeConfigPlugin.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintinghardware/FingerprintingHardwareFeaturePlugin.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingscreensize/FingerprintingScreenSizeContentScopeConfigPlugin.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingscreensize/FingerprintingScreenSizeFeaturePlugin.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingtemporarystorage/FingerprintingTemporaryStorageContentScopeConfigPlugin.kt
  fingerprint-protection/fingerprint-protection-impl/src/main/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingtemporarystorage/FingerprintingTemporaryStorageFeaturePlugin.kt
  fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/FingerprintProtectionSeedWorkerSchedulerTest.kt
  fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/FingerprintProtectionSeedWorkerTest.kt
  fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingbattery/FingerprintingBatteryContentScopeConfigPluginTest.kt
  fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingbattery/FingerprintingBatteryFeaturePluginTest.kt
  fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingcanvas/FingerprintingCanvasContentScopeConfigPluginTest.kt
  fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingcanvas/FingerprintingCanvasFeaturePluginTest.kt
  fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintinghardware/FingerprintingHardwareContentScopeConfigPluginTest.kt
  fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintinghardware/FingerprintingHardwareFeaturePluginTest.kt
  fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingscreensize/FingerprintingScreenSizeContentScopeConfigPluginTest.kt
  fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingscreensize/FingerprintingScreenSizeFeaturePluginTest.kt
  fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingtemporarystorage/FingerprintingTemporaryStorageContentScopeConfigPluginTest.kt
  fingerprint-protection/fingerprint-protection-impl/src/test/java/com/duckduckgo/fingerprintprotection/impl/features/fingerprintingtemporarystorage/FingerprintingTemporaryStorageFeaturePluginTest.kt
  fingerprint-protection/fingerprint-protection-store/.gitignore
  fingerprint-protection/fingerprint-protection-store/build.gradle
  fingerprint-protection/fingerprint-protection-store/src/main/AndroidManifest.xml
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/FingerprintProtectionDatabase.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/FingerprintProtectionEntities.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/features/fingerprintingbattery/FingerprintingBatteryDao.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/features/fingerprintingbattery/FingerprintingBatteryRepository.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/features/fingerprintingcanvas/FingerprintingCanvasDao.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/features/fingerprintingcanvas/FingerprintingCanvasRepository.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/features/fingerprintinghardware/FingerprintingHardwareDao.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/features/fingerprintinghardware/FingerprintingHardwareRepository.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/features/fingerprintingscreensize/FingerprintingScreenSizeDao.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/features/fingerprintingscreensize/FingerprintingScreenSizeRepository.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/features/fingerprintingtemporarystorage/FingerprintingTemporaryStorageDao.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/features/fingerprintingtemporarystorage/FingerprintingTemporaryStorageRepository.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/seed/FingerprintProtectionSeedDao.kt
  fingerprint-protection/fingerprint-protection-store/src/main/java/com/duckduckgo/fingerprintprotection/store/seed/FingerprintProtectionSeedRepository.kt
  fingerprint-protection/fingerprint-protection-store/src/test/java/com/duckduckgo/fingerprintprotection/store/features/fingerprintingbattery/RealFingerprintingBatteryRepositoryTest.kt
  fingerprint-protection/fingerprint-protection-store/src/test/java/com/duckduckgo/fingerprintprotection/store/features/fingerprintingcanvas/RealFingerprintingCanvasRepositoryTest.kt
  fingerprint-protection/fingerprint-protection-store/src/test/java/com/duckduckgo/fingerprintprotection/store/features/fingerprintinghardware/RealFingerprintingHardwareRepositoryTest.kt
  fingerprint-protection/fingerprint-protection-store/src/test/java/com/duckduckgo/fingerprintprotection/store/features/fingerprintingscreensize/RealFingerprintingScreenSizeRepositoryTest.kt
  fingerprint-protection/fingerprint-protection-store/src/test/java/com/duckduckgo/fingerprintprotection/store/features/fingerprintingtemporarystorage/RealFingerprintingTemporaryStorageRepositoryTest.kt
  fingerprint-protection/fingerprint-protection-store/src/test/java/com/duckduckgo/fingerprintprotection/store/seed/RealFingerprintProtectionSeedRepositoryTest.kt
Labels: STACKED PR - DO NOT MERGE

#2532 Move VPNCoroutineScope to :di module
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/debug/DeviceShieldNotificationsDebugReceiver.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/health/AppTPHealthMonitor.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/health/HealthMetricCounter.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldNotificationScheduler.kt
  di/src/main/java/com/duckduckgo/vpn/di/VpnCoroutineScope.kt
Labels: QA-Optional

#2555 Update reference tests to latest version
  app/src/android/resources/reference_tests/brokensites/tests.json
  package-lock.json
  package.json
Labels: reference tests, automated pr

#2570 Update reference tests to latest version
  app/src/androidTest/resources/reference_tests/domain_matching_tests.json
  app/src/androidTest/resources/reference_tests/surrogates.txt
  package-lock.json
  package.json
Labels: reference tests, automated pr

#2568 Update content scope scripts to 3.3.2
  node_modules/@duckduckgo/content-scope-scripts/LICENSE.md
  node_modules/@duckduckgo/content-scope-scripts/README.md
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: QA-Optional

#2576 ADS: Internal Features Settings migration
  app-tracking-protection/vpn-internal/src/main/java/com/duckduckgo/vpn/internal/feature/VpnInternalSettingsActivity.kt
  app-tracking-protection/vpn-internal/src/main/res/layout/activity_vpn_internal_settings.xml
  app/src/internal/res/layout/activity_audit_settings.xml
  app/src/internal/res/layout/activity_dev_settings.xml
  app/src/internal/res/values/donottranslate.xml
Labels: QA-Optional

#2551 Translations for autofill suggested label
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-ru/strings.xml
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-bg/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-cs/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-da/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-de/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-el/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-es/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-et/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-fi/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-fr/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-hr/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-hu/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-it/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-lt/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-lv/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-nb/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-nl/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-pl/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-pt/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-ro/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-ru/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-sk/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-sl/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-sv/strings-dashboard.xml
  privacy-dashboard/privacy-dashboard-impl/src/main/res/values-tr/strings-dashboard.xml
Labels: QA-Optional, Pending Translation
