Repository duckduckgo/Android, pull requests merged in 2022-10, with the labels that each got.

#2358 Add searchListener initialization check
  app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksActivity.kt
Labels: QA-Optional

#2355 Migrate maestro test to the new dashboard
  ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/10_-_m.js_bing-provided;_ad_domain_provided_but_incorrect_(dsl_not_needed).yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/11_-_y.js_bing-provided;_ad_domain_provided_but_it's_not_a_domain_(i.e.,_abcedf)_(u3_not_needed).yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/12_-_m.js_bing-provided;_ad_domain_provided_but_it's_not_a_domain_(i.e.,_abcedf)__(dsl_not_needed).yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/13_-_y.js_bing-provided;_ad_domain_provided_but_it's_a_subdomain_of_advertiser_(i.e.,_foo.www.search-company-site)_(u3_not_needed).yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/14_-_m.js_bing-provided;_ad_domain_provided_but_it's_a_subdomain_of_advertiser_(i.e.,_foo.www.search-company-site)__(dsl_not_needed).yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/1_-_y.js_heuristic;_no_ad_domain_param;_u3_param_included.yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/2_-_m.js_heuristic;_no_ad_domain_param;_dsl_param_included.yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/3_-_y.js_heuristic;_no_ad_domain_param,_but_missing_u3_param.yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/4_-_m.js_heuristic;_no_ad_domain_param,_but_missing_dsl_param.yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/5_-_y.js_heuristic;_ad_domain_provided,_but_empty_(u3_not_needed).yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/6_-_m.js_heuristic;_ad_domain_provided,_but_empty_(dsl_not_needed).yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/7_-_y.js_bing-provided;_ad_domain_provided_(u3_not_needed).yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/8_-_m.js_bing-provided;_ad_domain_provided_(dsl_not_needed).yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/ad_click_detection_flows/9_-_y.js_bing-provided;_ad_domain_provided_but_incorrect_(u3_not_needed).yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/1_-_Single-site,_single-tab,_session.yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/2_-_Single-site,_new-tab,_session.yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/3_-_Single-site,_new-tab,_session_variant_two.yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/4_-_Single-site,_multi-tab_session.yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/5_-_Multi-site,_single-tab,_session.yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/6_-_Multi-tab.yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/7_-_Browser_restart_mid-session.yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/8_-_Navigation_with_back_forward.yaml
  ad-click/ad-click-impl/src/test/resources/maestro_tests/privacy_test_pages/9_-_Navigation_with_refresh.yaml
Labels: STACKED PR - DO NOT MERGE

#2354 PD feature branch - enable back api dependency checks
  build.gradle
  privacy-dashboard/privacy-dashboard-api/build.gradle
Labels: STACKED PR - DO NOT MERGE, QA-Optional

#2346 Site Permissions new tests
  app/src/main/java/com/duckduckgo/app/di/PrivacyModule.kt
  app/src/main/java/com/duckduckgo/app/global/view/ClearPersonalDataAction.kt
  app/src/main/java/com/duckduckgo/app/sitepermissions/permissionsperwebsite/PermissionsPerWebsiteViewModel.kt
  app/src/test/java/com/duckduckgo/app/sitepermissions/PermissionsPerWebsiteViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/sitepermissions/SitePermissionsViewModelTest.kt
  site-permissions/site-permissions-api/src/main/java/com/duckduckgo/site/permissions/api/SitePermissionsManager.kt
  site-permissions/site-permissions-impl/build.gradle
  site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsManagerImpl.kt
  site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsRepository.kt
  site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/di/SitePermissionsModule.kt
  site-permissions/site-permissions-impl/src/test/java/com/duckduckgo/site/permissions/impl/SitePermissionsManagerTest.kt
  site-permissions/site-permissions-impl/src/test/java/com/duckduckgo/site/permissions/impl/SitePermissionsRepositoryImplTest.kt
  site-permissions/site-permissions-impl/src/test/java/com/duckduckgo/site/permissions/impl/SitePermissionsRepositoryTest.kt
Labels: QA-Optional

#2376 ADS: Fix Divider Lint
  lint-rules/src/main/java/com/duckduckgo/lint/ui/NoAlertDialogDetector.kt
  lint-rules/src/test/java/com/duckduckgo/lint/NoAlertDialogDetectorTest.kt
  lint-rules/src/test/java/com/duckduckgo/lint/ui/MissingDividerDetectorTest.kt
Labels: QA-Optional

#2347 Remove gpc.js
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/androidTest/java/com/duckduckgo/app/browser/urlextraction/UrlExtractingWebViewClientTest.kt
  app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
  app/src/main/java/com/duckduckgo/app/browser/urlextraction/UrlExtractingWebViewClient.kt
  privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/Gpc.kt
  privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/gpc/RealGpc.kt
  privacy-config/privacy-config-impl/src/main/res/raw/gpc.js
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/gpc/RealGpcTest.kt
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/gpc/GpcHeaderReferenceTest.kt
Labels: STACKED PR - DO NOT MERGE, QA-Optional

#2298 Add content scope scripts to node modules
  .gitignore
  app/build.gradle
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
  app/src/androidTest/java/com/duckduckgo/app/browser/urlextraction/UrlExtractingWebViewClientTest.kt
  app/src/androidTest/java/com/duckduckgo/app/referencetests/HttpsReferenceTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
  app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
  app/src/main/java/com/duckduckgo/app/browser/urlextraction/UrlExtractingWebViewClient.kt
  app/src/test/java/com/duckduckgo/app/browser/useragent/UserAgentProviderTest.kt
  autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/Fakes.kt
  content-scope-scripts/content-scope-scripts-api/.gitignore
  content-scope-scripts/content-scope-scripts-api/build.gradle
  content-scope-scripts/content-scope-scripts-api/src/main/java/com/duckduckgo/contentscopescripts/api/ContentScopeConfigPlugin.kt
  content-scope-scripts/content-scope-scripts-api/src/main/java/com/duckduckgo/contentscopescripts/api/ContentScopeScripts.kt
  content-scope-scripts/content-scope-scripts-impl/build.gradle
  content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/ContentScopeConfigPluginPoint.kt
  content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/ContentScopeJSReader.kt
  content-scope-scripts/content-scope-scripts-impl/src/main/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScripts.kt
  content-scope-scripts/content-scope-scripts-impl/src/test/java/com/duckduckgo/contentscopescripts/impl/RealContentScopeScriptsTest.kt
  node_modules/@duckduckgo/content-scope-scripts/LICENSE.md
  node_modules/@duckduckgo/content-scope-scripts/README.md
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
  privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/Gpc.kt
  privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/UnprotectedTemporary.kt
  privacy-config/privacy-config-impl/build.gradle
  privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/gpc/GpcContentScopeConfigPlugin.kt
  privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/gpc/GpcPlugin.kt
  privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/gpc/RealGpc.kt
  privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/features/unprotectedtemporary/RealUnprotectedTemporary.kt
  privacy-config/privacy-config-impl/src/main/res/raw/gpc.js
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/gpc/GpcContentScopeConfigPluginTest.kt
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/gpc/GpcPluginTest.kt
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/gpc/RealGpcTest.kt
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/unprotectedtemporary/RealUnprotectedTemporaryTest.kt
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/GpcHeaderReferenceTest.kt
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/GpcJavascriptReferenceTest.kt
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/gpc/GpcHeaderReferenceTest.kt
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/gpc/GpcJavascriptReferenceTest.kt
  privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabase.kt
  privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabaseModels.kt
  privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/gpc/GpcContentScopeConfigDao.kt
  privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/gpc/GpcRepository.kt
  privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/unprotectedtemporary/UnprotectedTemporaryRepository.kt
  privacy-config/privacy-config-store/src/test/java/com/duckduckgo/privacy/config/store/features/gpc/RealGpcRepositoryTest.kt
  privacy-config/privacy-config-store/src/test/java/com/duckduckgo/privacy/config/store/features/unprotectedtemporary/RealUnprotectedTemporaryRepositoryTest.kt
Labels: STACKED PR - DO NOT MERGE, QA-Optional

#2367 Update reference tests and use npm
  .gitignore
  app/src/android/resources/reference_tests/brokensites/tests.json
  app/src/androidTest/java/com/duckduckgo/app/referencetests/FirstPartyCookiesReferenceTest.kt
  app/src/androidTest/resources/reference_tests/domain_matching_tests.json
  app/src/androidTest/resources/reference_tests/firstpartycookies/config_reference.json
  app/src/androidTest/resources/reference_tests/firstpartycookies/tests.json
  app/src/androidTest/resources/reference_tests/https/tests.json
  app/src/androidTest/resources/reference_tests/surrogates.txt
  app/src/androidTest/resources/reference_tests/tracker_radar_reference.json
  copy-files-from-to.json
  package-lock.json
  package.json
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/amplinks/AmpFormatReferenceTest.kt
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/amplinks/AmpKeywordReferenceTest.kt
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/features/trackingparameters/TrackingParameterReferenceTest.kt
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/amplinks/amp_links_reference.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/amplinks/config_reference.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/amplinks/tests.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/gpc/config_reference.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/gpc/tests.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/privacyconfig/config1_reference.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/privacyconfig/config2_reference.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/privacyconfig/config3_reference.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/privacyconfig/tests.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackerallowlist/tracker_allowlist_matching_tests.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackerallowlist/tracker_allowlist_reference.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackingparameters/config_reference.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackingparameters/tests.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackingparameters/tracking_parameters_reference.json
Labels: QA-Optional

#2401 Fix flaky cookies test
  app/src/androidTest/java/com/duckduckgo/app/referencetests/FirstPartyCookiesReferenceTest.kt
Labels: QA-Optional

#2402 Remove port from URL before calling evaluate
  app/src/androidTest/resources/reference_tests/domain_matching_tests.json
  app/src/main/java/com/duckduckgo/app/trackerdetection/TdsClient.kt
Labels: QA-Optional

#2415 Hotfix/5.139.1
  app/src/main/AndroidManifest.xml
  app/version/release-notes
  app/version/version.properties
  site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsManagerImpl.kt
  site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/di/SitePermissionsModule.kt
  site-permissions/site-permissions-impl/src/test/java/com/duckduckgo/site/permissions/impl/SitePermissionsManagerTest.kt
Labels: HOTFIX DO NOT MERGE

#2409 Automate update ref tests
  .github/workflows/build-debug-apk.yaml
  .github/workflows/ci.yml
  .github/workflows/update-ref-tests.yml
Labels: QA-Optional

#2418 hotfix/5.139.2
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/integration/NgVpnNetworkStack.kt
  app/version/release-notes
  app/version/version.properties
Labels: HOTFIX DO NOT MERGE

#2425 Update reference tests to latest version
  package-lock.json
  package.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/gpc/tests.json
Labels: reference tests, automated pr

#2427 Make diff between +-5 seconds
  app/src/androidTest/java/com/duckduckgo/cookies/impl/features/firstparty/RealFirstPartyCookiesModifierTest.kt
Labels: QA-Optional

#2406 [Part 4] Implementation for Exclusion List in AppTP
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ManageAppsProtectionViewModel.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionExclusionListActivity.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedFragment.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/TrackerFeedAdapter.kt
  app-tracking-protection/vpn-impl/src/main/res/drawable/ic_arrow_down.xml
  app-tracking-protection/vpn-impl/src/main/res/drawable/ic_chevron_forward_small_24.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/activity_tracking_protection_exclusion_list.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/popup_window_exclusion_list_filter_item_menu.xml
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/apps/ManageAppsProtectionViewModelTest.kt
Labels: STACKED PR - DO NOT MERGE

#2437 [Final] Implementation for Exclusion List in AppTP
  app-tracking-protection/vpn-impl/src/main/AndroidManifest.xml
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ManageAppsProtectionViewModel.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/ManuallyDisableAppProtectionDialog.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/ManuallyEnableAppProtectionDialog.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionAppsAdapter.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionExclusionListActivity.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/breakage/ReportBreakageAppListAdapter.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedFragment.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModel.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModel.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/MultiAppsIcon.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/TrackerFeedAdapter.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/model/TrackerFeedItem.kt
  app-tracking-protection/vpn-impl/src/main/java/dummy/ui/VpnControllerActivity.kt
  app-tracking-protection/vpn-impl/src/main/res/drawable/ic_apptp_alert.xml
  app-tracking-protection/vpn-impl/src/main/res/drawable/ic_apptp_link.xml
  app-tracking-protection/vpn-impl/src/main/res/drawable/ic_chevron_forward_small_24.xml
  app-tracking-protection/vpn-impl/src/main/res/drawable/ic_oval_background.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/activity_device_shield_activity.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/activity_tracking_protection_exclusion_list.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/dialog_tracking_protection_manually_disable_app.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/dialog_tracking_protection_manually_enable_app.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_activity_apps.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_excluded_app_entry.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/view_multi_apps_icon.xml
  app-tracking-protection/vpn-impl/src/main/res/values-bg/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-cs/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-da/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-de/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-el/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-es/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-et/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-fi/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-fr/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-hr/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-hu/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-it/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-lt/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-lv/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-nb/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-nl/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-pl/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-pt/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-ro/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-ru/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-sk/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-sl/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-sv/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-tr/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn-untranslated.xml
  app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/apps/ManageAppsProtectionViewModelTest.kt
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModelTest.kt
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModelTest.kt
  common-ui/src/main/java/com/duckduckgo/mobile/android/ui/recyclerviewext/StickyHeadersLinearLayoutManager.kt
Labels: STACKED PR - DO NOT MERGE

#2434 Support updating username when matching password provided
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/autofill/AutofillCredentialsSelectionResultHandler.kt
  app/src/test/java/com/duckduckgo/app/browser/autofill/AutofillCredentialsSelectionResultHandlerTest.kt
  autofill/autofill-api/src/main/java/com/duckduckgo/autofill/AutofillCredentialDialogs.kt
  autofill/autofill-api/src/main/java/com/duckduckgo/autofill/store/AutofillStore.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/CredentialAutofillDialogAndroidFactory.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/updating/AutofillUpdatingExistingCredentialsDialogFragment.kt
  autofill/autofill-impl/src/main/res/layout/content_autofill_update_existing_credentials.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStore.kt
  autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/SecureStoreBackedAutofillStoreTest.kt
Labels: Pending Translation
