Repository duckduckgo/Android, pull requests merged in 2023-02, with the labels that each got.

#2777 Login user flow
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncRepository.kt
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncService.kt
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncServiceRemote.kt
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupActivity.kt
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupViewModel.kt
  sync/sync-impl/src/main/res/layout/activity_sync_setup.xml
  sync/sync-impl/src/test/java/com/duckduckgo/sync/AppSyncDeviceIdsTest.kt
  sync/sync-impl/src/test/java/com/duckduckgo/sync/TestSyncFixtures.kt
  sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncRepositoryTest.kt
  sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/SyncServiceRemoteTest.kt
  sync/sync-store/src/main/java/com/duckduckgo/sync/store/SyncStore.kt
Labels: STACKED PR - DO NOT MERGE

#2759 Create account user flow
  sync/sync-impl/build.gradle
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncDeviceId.kt
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncRepository.kt
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncService.kt
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncServiceRemote.kt
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/di/SyncModule.kt
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupActivity.kt
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupViewModel.kt
  sync/sync-impl/src/main/res/layout/activity_sync_setup.xml
  sync/sync-impl/src/test/java/com/duckduckgo/sync/AppSyncDeviceIdsTest.kt
  sync/sync-impl/src/test/java/com/duckduckgo/sync/TestSyncFixtures.kt
  sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncRepositoryTest.kt
  sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/SyncServiceRemoteTest.kt
  sync/sync-lib/src/main/java/com/duckduckgo/sync/crypto/SyncNativeLib.kt
  sync/sync-store/src/main/java/com/duckduckgo/sync/store/SyncStore.kt
Labels: STACKED PR - DO NOT MERGE

#2737 Sync settings test screen skeleton
  app/build.gradle
  app/src/internal/java/com/duckduckgo/app/sync/InternalSyncFeature.kt
  app/src/internal/res/values/donottranslate.xml
  sync/sync-api/.gitignore
  sync/sync-api/build.gradle
  sync/sync-impl/.gitignore
  sync/sync-impl/build.gradle
  sync/sync-impl/lint-baseline.xml
  sync/sync-impl/proguard-rules.pro
  sync/sync-impl/src/main/AndroidManifest.xml
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncDeviceId.kt
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupActivity.kt
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupViewModel.kt
  sync/sync-impl/src/main/res/layout/activity_sync_setup.xml
  sync/sync-impl/src/main/res/values/donottranslate.xml
Labels: STACKED PR - DO NOT MERGE

#2811 Update reference tests to latest version
  package-lock.json
  package.json
Labels: reference tests, automated pr

#2820 Fire error pixel only when onCreaterVpn() is failure
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/TrackerBlockingVpnService.kt
Labels: QA-Optional

#2807 Part 3 - Address feedback
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModel.kt
  app-tracking-protection/vpn-impl/src/main/res/layout/activity_device_shield_activity.xml
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNamesTest.kt
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/downloads/DownloadsAdapter.kt
  app/src/main/java/com/duckduckgo/app/downloads/DownloadsItemListener.kt
  app/src/main/java/com/duckduckgo/app/downloads/DownloadsViewModel.kt
  app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
  app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
  app/src/main/res/layout/content_settings_customize.xml
  app/src/main/res/layout/view_item_downloads_notify_me.xml
  app/src/main/res/values/donottranslate.xml
  app/src/test/java/com/duckduckgo/app/downloads/DownloadsViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/global/api/AtpPixelRemovalInterceptorTest.kt
  app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/statistics/pixels/PixelNameTest.kt
  common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/component/Component.kt
  common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/component/ComponentOtherFragment.kt
  common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/component/ComponentViewHolder.kt
  common-ui/src/main/java/com/duckduckgo/mobile/android/ui/notifyme/NotifyMeView.kt
  common-ui/src/main/java/com/duckduckgo/mobile/android/ui/notifyme/NotifyMeViewModel.kt
  common-ui/src/main/res/layout/component_notify_me.xml
  common-ui/src/main/res/layout/view_notify_me_view.xml
  common-ui/src/main/res/values/attrs-notify-me-view.xml
  common-ui/src/test/java/com/duckduckgo/mobile/android/ui/notifyme/NotifyMeViewModelTest.kt
  statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Labels: STACKED PR - DO NOT MERGE

#2829 Update reference tests to latest version
  package-lock.json
  package.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/gpc/tests.json
Labels: reference tests, automated pr

#2825 Ensure credential list items don't have their text clipped
  autofill/autofill-impl/src/main/res/layout/item_row_autofill_credentials_management_screen.xml
Labels: QA-Optional

#2826 Fix empty autofill placeholder color
  autofill/autofill-impl/src/main/res/drawable/ic_autofill_keychain.xml
Labels: QA-Optional

#2835 Update hiring release notes
  app/version/release-notes-hiring
Labels: QA-Optional

#2834 Update title of autofill picker dialog
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Labels: Pending Translation

#2845 Report Broken Site screen not symmetrical
  app/src/main/res/layout/content_broken_sites.xml
Labels: QA-Optional

#2841 Update reference tests to latest version
  package-lock.json
  package.json
Labels: reference tests, automated pr

#2853 Migrate ReportBreakageAppListAdapter
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/breakage/ReportBreakageAppListAdapter.kt
Labels: QA-Optional

#2854 Migrate AppTPCompanyTrackersActivity
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/AppTPCompanyTrackersActivity.kt
Labels: QA-Optional

#2855 Migrate PastWeekTrackerActivityContentView
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/PastWeekTrackerActivityContentView.kt
Labels: QA-Optional

#2852 Migrate TrackingProtectionAppsAdapter
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionAppsAdapter.kt
Labels: QA-Optional

#2862 Let privacy workflow execute manually
  .github/workflows/privacy.yml
Labels: QA-Optional

#2863 Update content scope scripts to latest version
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#2861 AppTP: Remove the kotlin-android-extensions plugin
  app-tracking-protection/vpn-impl/build.gradle
Labels: QA-Optional

#2865 Remove redundant autofill formatter class
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/AutofillDomainFormatter.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/AutofillDomainFormatterDomainNameOnlyTest.kt
Labels: QA-Optional

#2868 Ensure autofill login list headings' widths aren't clipped
  autofill/autofill-impl/src/main/res/layout/item_row_autofill_credentials_management_screen_header.xml
Labels: QA-Optional

#2871 Add GB to europeanCountries list
  app/version/version.properties
  statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Labels: QA-Optional

#2872 Merge changes from main back into develop
  app/version/version.properties
  statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Labels: QA-Optional

#2873 Upgrade version.androidx.work - AppTP should not specify a different version as that is not used
  app-tracking-protection/vpn-impl/build.gradle
Labels: QA-Optional

#2879 Update content scope scripts to latest version
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#2880 Android: Crash in PrivacyConfigDatabaseKt$MIGRATION_10_11$
  privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabase.kt
Labels: QA-Optional
