Repository duckduckgo/Android, pull requests merged in 2023-11, with the labels that each got.

#3794 Fix sync env endpoint rewrite logic
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/internal/SyncInternalEnvInterceptor.kt
Labels: QA-Optional

#3792 Update reference tests to version 1698918761
  package-lock.json
  package.json
Labels: reference tests, automated pr

#3793 Update content scope scripts to version 4.42.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3800 Update content scope scripts to version 4.43.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3805 Add readmes
  autoconsent/readme.md
  common/readme.md
  cookies/readme.md
  internal-features/readme.md
  js-messaging/readme.md
  macos/readme.md
  privacy-config/readme.md
  request-filterer/readme.md
  settings/readme.md
  subscriptions/readme.md
  user-agent/readme.md
Labels: QA-Optional

#3810 Update content scope scripts to version 4.44.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3836 Update reference tests to version 1699439919
  app/src/androidTest/java/com/duckduckgo/app/referencetests/SurrogatesReferenceTest.kt
  app/src/androidTest/resources/reference_tests/domain_matching_tests.json
  app/src/androidTest/resources/reference_tests/tracker_radar_reference.json
  app/src/test/resources/reference_tests/brokensites/multiple_report_tests.json
  package-lock.json
  package.json
Labels: reference tests, automated pr

#3837 Update content scope scripts to version 4.45.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3848 Update content scope scripts to version 4.46.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3849 Update reference tests to version 1699613603
  app/src/test/resources/reference_tests/brokensites/multiple_report_tests.json
  app/src/test/resources/reference_tests/brokensites/tests.json
  package-lock.json
  package.json
Labels: reference tests, automated pr

#3854 Fix casing on test expectation to ensure it matches the app
  .maestro/app_tp/app_tp_onboarding.yaml
Labels: QA-Optional

#3861 Update content scope scripts to version 4.48.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3813 Standardize traces namespace
  app/src/internal/java/com/duckduckgo/app/dev/settings/DevSettingsViewModel.kt
  traces/traces-api/build.gradle
  traces/traces-api/src/main/java/com/duckduckgo/traces/api/StartupTraces.kt
  traces/traces-impl/build.gradle
  traces/traces-impl/src/main/AndroidManifest.xml
  traces/traces-impl/src/main/java/com/duckduckgo/traces/impl/AppStartUpTracer.kt
  traces/traces-impl/src/main/java/com/duckduckgo/traces/impl/RealStartupTraces.kt
Labels: STACKED PR - DO NOT MERGE

#3818 Standardize macos namespace
  macos/macos-impl/build.gradle
  macos/macos-impl/src/main/AndroidManifest.xml
  macos/macos-impl/src/main/java/com/duckduckgo/macos/impl/MacOsActivity.kt
  macos/macos-impl/src/main/java/com/duckduckgo/macos/impl/MacOsLinkShareBroadcastReceiver.kt
  macos/macos-impl/src/main/java/com/duckduckgo/macos/impl/MacOsPixelNames.kt
  macos/macos-impl/src/main/java/com/duckduckgo/macos/impl/MacOsViewModel.kt
  macos/macos-impl/src/main/res/layout/activity_macos.xml
  macos/macos-impl/src/test/java/com/duckduckgo/macos/impl/MacOsViewModelTest.kt
Labels: STACKED PR - DO NOT MERGE

#3872 Update content scope scripts to version 4.50.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3878 Remove temporary pixel for system autofill
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoWebView.kt
  autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/systemautofill/SystemAutofillUsageMonitor.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/systemautofill/RealSystemAutofillUsageMonitor.kt
Labels: QA-Optional

#3879 Update content scope scripts to version 4.51.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3883 Fix null pointers in unit tests
  app/src/test/java/com/duckduckgo/app/firebutton/FireButtonViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
  network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/management/NetworkProtectionManagementViewModelTest.kt
  sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/ui/SyncActivityViewModelTest.kt
Labels: QA-Optional

#3884 Attempt to fix test failing due to exceeding 10s timeout
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
Labels: QA-Optional

#3892 Fix okhttp3 NullPointerException
  versions.properties
Labels: QA-Optional

#3896 Calculate lint version automatically instead of hardcoding specific version
  build.gradle
Labels: QA-Optional

#3910 Update content scope scripts to version 4.52.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3922 Update content scope scripts to version 4.53.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3928 Remove unused autofill system service pixel name
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
Labels: QA-Optional

#3942 Move ic_image_24 to common-ui so it can be used elsewhere (also, fixes alpha value for it)
  common/common-ui/src/main/res/drawable/ic_image_24.xml
  sync/sync-impl/src/main/res/drawable/ic_image_24.xml
Labels: QA-Optional

#3941 Rename site-permissions camera icon
  app/src/main/java/com/duckduckgo/app/sitepermissions/SitePermissionsAdapter.kt
  app/src/main/java/com/duckduckgo/app/sitepermissions/permissionsperwebsite/PermissionsPerWebsiteViewModel.kt
  app/src/main/res/drawable/ic_video_24.xml
  app/src/main/res/drawable/ic_video_blocked_24.xml
  app/src/test/java/com/duckduckgo/app/sitepermissions/PermissionsPerWebsiteViewModelTest.kt
Labels: QA-Optional
