Repository duckduckgo/Android, pull requests merged in 2023-04, with the labels that each got.

#3033 Update content scope scripts to latest version
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3030 Fix OneLineListItem iconRes
  common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/listitem/OneLineListItem.kt
Labels: QA-Optional

#3037 Disable Optimise Onboarding Experiment
  app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
  statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Labels: QA-Optional

#3038 Enable Onboarding Cutomization Experiment
  app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
  statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Labels: QA-Optional

#3036 Translations for confirmation dialog
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
  device-auth/device-auth-impl/src/main/res/values-bg/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-cs/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-da/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-de/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-el/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-es/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-et/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-fi/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-fr/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-hr/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-hu/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-it/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-lt/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-lv/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-nb/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-nl/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-pl/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-pt/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-ro/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-ru/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-sk/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-sl/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-sv/strings-device-auth.xml
  device-auth/device-auth-impl/src/main/res/values-tr/strings-device-auth.xml
Labels: QA-Optional, Pending Translation

#3046 Fix notifications maestro tests
  .maestro/notifications_permissions_android13_plus/1_-_permissions_allowed.yaml
  .maestro/notifications_permissions_android13_plus/2_-_permissions_denied.yaml
Labels: QA-Optional

#3047 Update content scope scripts to latest version
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3051 Ensure that minSupportedVersion for subfeatures is parsed as int
  anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
Labels: QA-Optional

#3060 Ignore flakey cookie test
  app/src/androidTest/java/com/duckduckgo/cookies/impl/features/firstparty/RealFirstPartyCookiesModifierTest.kt
Labels: QA-Optional

#3068 Better handle attempt to launch settings for securing device
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementDisabledMode.kt
Labels: QA-Optional

#3079 Delete flaky test
  app/src/androidTest/java/com/duckduckgo/cookies/impl/features/firstparty/RealFirstPartyCookiesModifierTest.kt
Labels: QA-Optional

#3081 Add external reference test workflow
  .github/workflows/external-ref-tests.yml
Labels: QA-Optional

#3095 Ensure we catch ActivityNotFoundExceptions when opening external app links
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Labels: QA-Optional

#3103 Update content scope scripts to latest version
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3109 Remove testing deprecated methods
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncRepository.kt
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupActivity.kt
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/ui/SyncInitialSetupViewModel.kt
  sync/sync-impl/src/main/res/layout/activity_sync_setup.xml
  sync/sync-impl/src/test/java/com/duckduckgo/sync/AppSyncDeviceIdsTest.kt
  sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncRepositoryTest.kt
  sync/sync-store/src/main/java/com/duckduckgo/sync/store/SyncStore.kt
Labels: QA-Optional
