Repository duckduckgo/Android, pull requests merged in 2023-05, with the labels that each got.

#3150 Remove OnSharedPreferenceChangeListener in VpnFeatureRegistryImL
  app-tracking-protection/vpn-api-test/src/main/java/com/duckduckgo/mobile/android/vpn/FakeVpnFeaturesRegistry.kt
  app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/VpnFeaturesRegistry.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/VpnFeaturesRegistryImpl.kt
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/VpnFeaturesRegistryImplTest.kt
Labels: QA-Optional

#3153 Update reference tests to latest version
  package-lock.json
  package.json
Labels: reference tests, automated pr

#3157 Update reference tests to latest version
  app/src/androidTest/resources/reference_tests/domain_matching_tests.json
  app/src/androidTest/resources/reference_tests/tracker_radar_reference.json
  package-lock.json
  package.json
Labels: reference tests, automated pr

#3152 Android: Translations for the removal of windows waitlist in the Android app
  windows/windows-impl/src/main/res/values-bg/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-cs/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-da/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-de/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-el/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-es/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-et/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-fi/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-fr/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-hr/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-hu/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-it/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-lt/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-lv/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-nb/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-nl/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-pl/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-pt/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-ro/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-ru/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-sk/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-sl/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-sv/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-tr/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values/strings-waitlist-windows.xml
Labels: QA-Optional, Translations Request

#3162 Update reference tests to latest version
  app/src/androidTest/resources/reference_tests/domain_matching_tests.json
  app/src/androidTest/resources/reference_tests/tracker_radar_reference.json
  package-lock.json
  package.json
Labels: reference tests, automated pr

#3164 Update reference tests to latest version
  app/src/androidTest/resources/reference_tests/https/tests.json
  package-lock.json
  package.json
Labels: reference tests, automated pr

#3160 Update breakage reporting copy
  app-tracking-protection/vpn-impl/src/main/res/values-bg/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-cs/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-da/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-de/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-el/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-es/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-et/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-fi/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-fr/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-hr/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-hu/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-it/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-lt/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-lv/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-nb/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-nl/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-pl/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-pt/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-ro/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-ru/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-sk/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-sl/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-sv/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-tr/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn.xml
Labels: QA-Optional

#3168 Remove device prefix (json sync)
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncService.kt
Labels: QA-Optional

#3163 Android: Update windows description string
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  windows/windows-impl/src/main/res/values-bg/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-cs/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-da/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-de/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-el/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-es/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-et/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-fi/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-fr/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-hr/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-hu/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-it/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-lt/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-lv/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-nb/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-nl/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-pl/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-pt/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-ro/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-ru/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-sk/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-sl/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-sv/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values-tr/strings-waitlist-windows.xml
  windows/windows-impl/src/main/res/values/strings-waitlist-windows.xml
Labels: Translations Request

#3183 Add exceptPlatforms to AMP links and tracking parameter reference tests
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/amplinks/AmpFormatReferenceTest.kt
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/amplinks/AmpKeywordReferenceTest.kt
  privacy-config/privacy-config-impl/src/test/java/com/duckduckgo/privacy/config/impl/referencetests/trackingparameters/TrackingParameterReferenceTest.kt
Labels: QA-Optional

#3184 Set inputType on url field to avoid autocorrect/capitalisation
  autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_edit_mode.xml
Labels: QA-Optional

#3190 Update content scope scripts to latest version
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3189 Update reference tests to latest version
  app/src/androidTest/resources/reference_tests/domain_matching_tests.json
  app/src/androidTest/resources/reference_tests/tracker_radar_reference.json
  package-lock.json
  package.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackingparameters/tests.json
Labels: reference tests, automated pr

#3210 Add extra log statement which shows whether config will be persisted or not
  privacy-config/privacy-config-impl/src/main/java/com/duckduckgo/privacy/config/impl/PrivacyConfigPersister.kt
Labels: QA-Optional

#3215 Replace usage of get() to lazy for sharepreferences
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/pixels/AdClickPixels.kt
  ad-click/ad-click-store/src/main/java/com/duckduckgo/adclick/store/AdClickFeatureToggleStore.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/cohort/CohortStore.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/feature/AppTpPrivacyFeaturePlugin.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/prefs/VpnPreferences.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/VpnStore.kt
  app/src/internal/java/com/duckduckgo/app/dev/settings/db/DevSettingsDataStore.kt
  app/src/main/java/com/duckduckgo/app/accessibility/data/AccessibilityDataStore.kt
  app/src/main/java/com/duckduckgo/app/fire/UnsentForgetAllPixelStore.kt
  app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
  app/src/main/java/com/duckduckgo/app/global/install/AppInstallStore.kt
  app/src/main/java/com/duckduckgo/app/global/migrations/MigrationStore.kt
  app/src/main/java/com/duckduckgo/app/onboarding/store/OnboardingSharedPreferences.kt
  app/src/main/java/com/duckduckgo/app/referral/AppReferrerDataStore.kt
  app/src/main/java/com/duckduckgo/app/settings/db/SettingsDataStore.kt
  app/src/main/java/com/duckduckgo/widget/WidgetPreferences.kt
  autoconsent/autoconsent-store/src/main/java/com/duckduckgo/autoconsent/store/AutoconsentFeatureToggleStore.kt
  autoconsent/autoconsent-store/src/main/java/com/duckduckgo/autoconsent/store/AutoconsentSettingsDataStore.kt
  autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/InternalTestUserStore.kt
  common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/AppComponentsActivity.kt
  common-ui/src/main/java/com/duckduckgo/mobile/android/ui/store/ThemingSharedPreferences.kt
  common-ui/src/main/java/com/duckduckgo/mobile/android/ui/store/notifyme/NotifyMeSharedPreferences.kt
  cookies/cookies-store/src/main/java/com/duckduckgo/cookies/store/CookiesFeatureToggleStore.kt
  installation/installation-impl/src/main/java/com/duckduckgo/installation/impl/installer/InstallSourceLifecycleObserver.kt
  network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/cohort/NetpCohortStore.kt
  network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/pixels/NetworkProtectionPixels.kt
  network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/waitlist/store/NetPWaitlistDataStore.kt
  network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/network/NetPInternalExclusionListProvider.kt
  network-protection/network-protection-internal/src/main/java/com/duckduckgo/networkprotection/internal/network/NetPInternalMtuProvider.kt
  privacy-config/privacy-config-internal/src/main/java/com/duckduckgo/privacy/config/internal/store/DevPrivacyConfigSettingsDataStore.kt
  privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyFeatureTogglesDataStore.kt
  privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/features/gpc/GpcDataStore.kt
  request-filterer/request-filterer-store/src/main/java/com/duckduckgo/request/filterer/store/RequestFiltererFeatureToggleStore.kt
  site-permissions/site-permissions-store/src/main/java/com/duckduckgo/site/permissions/store/SitePermissionsPreferences.kt
  statistics/src/main/java/com/duckduckgo/app/statistics/pixels/FeatureRetentionPixelSender.kt
  statistics/src/main/java/com/duckduckgo/app/statistics/store/StatisticsSharedPreferences.kt
  traces/traces-impl/src/main/java/com/duckduckgo/app/traces/RealStartupTraces.kt
  voice-search/voice-search-store/src/main/java/com/duckduckgo/voice/store/VoiceSearchDataStore.kt
  windows/windows-store/src/main/java/com/duckduckgo/windows.store/WindowsWaitlistDataStore.kt
Labels: QA-Optional

#3217 Expose API for app categories
  app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/exclusion/AppCategory.kt
  app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/exclusion/AppCategoryDetector.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ApplicationInfoExtensions.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/NewAppBroadcastReceiver.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/RealAppCategoryDetector.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/TrackingProtectionAppInfo.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/TrackingProtectionAppsRepository.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/bugreport/VpnAppTrackerListInfoCollector.kt
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/UnprotectedAppsBucketPixelSenderTest.kt
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/apps/ManageAppsProtectionViewModelTest.kt
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/breakage/ReportBreakageAppListViewModelTest.kt
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/bugreport/VpnAppTrackerListInfoCollectorTest.kt
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModelTest.kt
  network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/exclusion/AppInfoExtensions.kt
  network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/exclusion/NetPExclusionList.kt
  network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/exclusion/TrackingProtectionAppInfo.kt
  network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/exclusion/NetPExclusionListTest.kt
Labels: QA-Optional

#3203 Update autofill copy and trigger translations
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/selecting/CredentialTextExtractorTest.kt
  macos/macos-impl/src/main/res/values-sl/strings-macos-waitlist.xml
  windows/windows-impl/src/main/res/values-fr/strings-waitlist-windows.xml
Labels: QA-Optional

#3219 Update reference tests to latest version
  app/src/androidTest/resources/reference_tests/domain_matching_tests.json
  app/src/androidTest/resources/reference_tests/tracker_radar_reference.json
  package-lock.json
  package.json
Labels: reference tests, automated pr

#3211 Android: Remove android.arch.persistence.room dependencies
  saved-sites/saved-sites-store/build.gradle
  sync/sync-store/build.gradle
  versions.properties
Labels: QA-Optional

#3216 ADS: Allow set endIcon programmatically on TextInput component
  common-ui/src/main/java/com/duckduckgo/mobile/android/themepreview/ui/component/textinput/ComponentTextInputFragment.kt
  common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/text/DaxTextInput.kt
  common-ui/src/main/res/layout/component_text_input_view.xml
Labels: QA-Optional
