Repository duckduckgo/Android, pull requests merged in 2023-01, with the labels that each got.

#2696 Create asana task when nightly workflows fail
  .github/workflows/end-to-end.yml
  .github/workflows/nightly.yml
  .github/workflows/privacy.yml
  .github/workflows/update-ref-tests.yml
Labels: QA-Optional

#2688 Remove tint on search drawable
  autofill/autofill-impl/src/main/res/drawable/ic_baseline_search_24.xml
Labels: QA-Optional

#2722 Flag our internal password field as unimportant for autofill
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt
Labels: QA-Optional

#2723 Update reference tests to latest version
  app/src/androidTest/resources/reference_tests/domain_matching_tests.json
  app/src/androidTest/resources/reference_tests/tracker_radar_reference.json
  app/src/main/java/com/duckduckgo/app/trackerdetection/TdsClient.kt
  app/src/main/java/com/duckduckgo/app/trackerdetection/api/TdsJson.kt
  app/src/main/java/com/duckduckgo/app/trackerdetection/model/TdsTracker.kt
  app/src/test/java/com/duckduckgo/app/trackerdetection/api/TdsTrackerJsonTest.kt
  app/src/test/resources/json/tds_trackers_action_invalid.json
  package-lock.json
  package.json
Labels: QA-Optional, reference tests, automated pr

#2731 Ignore same entity CNAMEs
  app/src/androidTest/resources/reference_tests/domain_matching_tests.json
  app/src/main/java/com/duckduckgo/app/trackerdetection/CloakedCnameDetector.kt
  app/src/test/java/com/duckduckgo/app/trackerdetection/CloakedCnameDetectorImplTest.kt
Labels: QA-Optional

#2736 Update reference tests to latest version
  package-lock.json
  package.json
Labels: reference tests, automated pr

#2742 Implementation task: Add pixel (updated to use OS version)
  app/src/main/java/com/duckduckgo/app/onboarding/di/WelcomePageModule.kt
  app/src/main/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPageViewModel.kt
  app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModel.kt
  app/src/test/java/com/duckduckgo/app/onboarding/ui/page/DefaultBrowserPageViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModelTest.kt
  statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Labels: STACKED PR - DO NOT MERGE

#2749 Fix internal dev interceptor
  privacy-config/privacy-config-internal/src/main/java/com/duckduckgo/privacy/config/internal/plugins/ApiDevPrivacyConfigInterceptor.kt
Labels: QA-Optional

#2760 Add additional scroll in release apptp onboarding
  .maestro/release_tests/5_-_app_tp_onboarding.yaml
Labels: QA-Optional

#2768 Update workflows concurrency
  .github/workflows/ci.yml
  .github/workflows/end-to-end.yml
  .github/workflows/nightly.yml
  .github/workflows/privacy-dashboard-end-to-end.yml
  .github/workflows/privacy.yml
  .github/workflows/update-ref-tests.yml
Labels: QA-Optional

#2784 Add new lint rule to avoid robolectric runner
  ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickManagerTest.kt
  ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/pixels/RealAdClickPixelsTest.kt
  app/build.gradle
  app/src/androidTest/java/com/duckduckgo/app/browser/WebViewDataManagerTest.kt
  app/src/androidTest/java/com/duckduckgo/app/referencetests/FireproofingReferenceTest.kt
  app/src/androidTest/java/com/duckduckgo/app/referencetests/FirstPartyCookiesReferenceTest.kt
  app/src/androidTest/java/com/duckduckgo/cookies/impl/SQLCookieRemoverTest.kt
  app/src/androidTest/java/com/duckduckgo/cookies/impl/features/firstparty/RealFirstPartyCookiesModifierTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/suggestion/SuggestionListBuilderTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/suggestion/SuggestionMatcherTest.kt
  autofill/autofill-store/src/test/java/com/duckduckgo/autofill/store/urlmatcher/AutofillDomainNameUrlMatcherTest.kt
  cookies/cookies-impl/src/test/java/com/duckduckgo/cookies/impl/WebViewCookieManagerTest.kt
  downloads/downloads-impl/src/test/java/com/duckduckgo/downloads/impl/PendingFileDownloadCompressTest.kt
  gradle/android-library.gradle
  lint-rules/src/main/java/com/duckduckgo/lint/NoRobolectricTestRunnerDetector.kt
  lint-rules/src/main/java/com/duckduckgo/lint/registry/DuckDuckGoIssueRegistry.kt
  lint-rules/src/test/java/com/duckduckgo/lint/NoRobolectricTestRunnerDetectorTest.kt
  robolectric.properties
  secure-storage/secure-storage-store/build.gradle
  secure-storage/secure-storage-store/src/test/java/com/duckduckgo/securestorage/store/RealSecureStorageRepositoryTest.kt
  site-permissions/site-permissions-impl/build.gradle
  site-permissions/site-permissions-impl/src/test/java/com/duckduckgo/site/permissions/impl/SitePermissionsManagerTest.kt
  site-permissions/site-permissions-impl/src/test/java/com/duckduckgo/site/permissions/impl/SitePermissionsRepositoryTest.kt
Labels: QA-Optional

#2788 Add message to assertion to try and figure out why a test is flaky
  app/src/androidTest/java/com/duckduckgo/cookies/impl/features/firstparty/RealFirstPartyCookiesModifierTest.kt
Labels: QA-Optional

#2791 ADS: Maestro Flow Fix
  .maestro/ads_preview_flows/1-_design-system-components.yaml
Labels: QA-Optional
