Repository duckduckgo/Android, pull requests merged in 2023-03, with the labels that each got.

#2890 Fix styles used on the bottom sheet URLs
  autofill/autofill-impl/src/main/res/layout/content_autofill_save_new_credentials.xml
  autofill/autofill-impl/src/main/res/layout/content_autofill_select_credentials_tooltip.xml
  autofill/autofill-impl/src/main/res/layout/content_autofill_update_existing_credentials.xml
  autofill/autofill-impl/src/main/res/values/styles.xml
Labels: QA-Optional

#2907 Update autofill save dialog subtitle
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Labels: QA-Optional

#2888 Fix code formatting issues in ContributesRemoteFeatureCodeGenerator
  anvil/anvil-compiler/src/main/java/com/duckduckgo/anvil/compiler/ContributesRemoteFeatureCodeGenerator.kt
Labels: QA-Optional

#2919 Update content scope scripts to latest version
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#2925 Update content scope scripts to latest version
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#2924 Update reference tests to latest version
  package-lock.json
  package.json
Labels: reference tests, automated pr

#2923 Update Robolectric from 4.9.1 to 4.9.2
  versions.properties
Labels: QA-Optional

#2955 Smartling translations for new onboarding options experiment
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
Labels: QA-Optional

#2963 Update content scope scripts to latest version
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#2965 Move VPNDetector to vpn-api
  app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/network/ExternalVpnDetector.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/network/RealVpnDetector.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/onboarding/VpnOnboardingViewModel.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModel.kt
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivityViewModelTest.kt
Labels: QA-Optional

#2968 Update reference tests to latest version
  app/src/androidTest/resources/reference_tests/domain_matching_tests.json
  app/src/androidTest/resources/reference_tests/tracker_radar_reference.json
  package-lock.json
  package.json
Labels: reference tests, automated pr

#2972 Restart CPM experiment
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
  autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/RealAutoconsentTest.kt
  autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/handlers/InitMessageHandlerPluginTest.kt
  common-ui/src/main/java/com/duckduckgo/mobile/android/ui/view/LottieDaxDialog.kt
  statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Labels: QA-Optional

#2982 Fix Maestro Favourites Assertions
  .maestro/release_tests/3_-_favorites.yaml
Labels: QA-Optional

#2983 Smartling: Translations for "Skip This Step"
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
Labels: QA-Optional

#2986 ADS: Add CODEOWNERS file
  .github/CODEOWNERS
Labels: QA-Optional

#2991 Move search icon to common-ui module
  common-ui/src/main/res/drawable/ic_find_search_24.xml
Labels: QA-Optional

#3002 ADS: DaxTextInput Hide Password Icon
  common-ui/src/main/res/drawable/ic_password_hide.xml
Labels: QA-Optional

#2990 Update content scope scripts to latest version
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#2999 DAU Pixel
  app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserDetector.kt
  app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
  app/src/main/java/com/duckduckgo/app/email/AppEmailManager.kt
  app/src/main/java/com/duckduckgo/app/email/di/EmailModule.kt
  app/src/main/java/com/duckduckgo/app/global/api/AtbAndAppVersionPixelRemovalInterceptor.kt
  statistics/build.gradle
  statistics/src/main/java/com/duckduckgo/app/statistics/api/BrowserFeatureStateReporterPlugin.kt
  statistics/src/main/java/com/duckduckgo/app/statistics/pixels/FeatureRetentionPixelSender.kt
  statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Labels: QA-Optional

#3008 Update content scope scripts to latest version
  node_modules/@duckduckgo/content-scope-scripts/README.md
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3016 Update content scope scripts to latest version
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3011 Update reference tests to latest version
  app/src/androidTest/resources/reference_tests/domain_matching_tests.json
  app/src/androidTest/resources/reference_tests/tracker_radar_reference.json
  package-lock.json
  package.json
Labels: reference tests, automated pr

#3021 Update reference tests to latest version
  app/src/androidTest/resources/reference_tests/domain_matching_tests.json
  package-lock.json
  package.json
Labels: reference tests, automated pr
