Repository duckduckgo/Android, pull requests merged in 2023-12, with the labels that each got.

#3667 Remove AppTP Beta label in settings
  .maestro/app_tp/app_tp_onboarding.yaml
  app-tracking-protection/vpn-impl/src/main/res/values-bg/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-cs/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-da/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-de/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-el/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-es/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-et/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-fi/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-fr/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-hr/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-hu/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-it/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-lt/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-lv/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-nb/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-nl/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-pl/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-pt/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-ro/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-ru/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-sk/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-sl/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-sv/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-tr/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values/strings-vpn.xml
  app/src/main/res/layout/content_settings_privacy.xml
Labels: STACKED PR - DO NOT MERGE

#3965 Fix/craig/fix outstanding translations l10n
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
Labels: QA-Optional

#3954 Support taking a new photo when prompted to upload an image
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/camera/CameraHardwareChecker.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/camera/CameraCaptureResultHandler.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/camera/launcher/UploadFromExternalCameraLauncher.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/camera/permission/RealExternalCameraSystemPermissionsHelper.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/camera/postprocess/CameraCaptureDelayedDeleter.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/camera/postprocess/CameraCaptureImageMover.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/camera/postprocess/DeleteCameraCaptureWorker.kt
  app/src/main/res/values/donottranslate.xml
  common/common-ui/src/main/res/drawable/ic_camera_24.xml
Labels: BLOCKED: DO NOT MERGE

#3992 Update content scope scripts to version 4.55.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3986 Trigger translations for uploading an image from the camera
  app-tracking-protection/vpn-impl/src/main/res/values-el/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-it/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-lv/strings-vpn.xml
  app-tracking-protection/vpn-impl/src/main/res/values-ru/strings-vpn.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/donottranslate.xml
  app/src/main/res/values/strings.xml
Labels: QA-Optional

#3983 Sync: Improve lists mechanism - patch request
  app/src/main/java/com/duckduckgo/app/di/DaoModule.kt
  app/src/test/java/com/duckduckgo/app/bookmarks/model/SyncSavedSitesRepositoryTest.kt
  app/src/test/java/com/duckduckgo/app/sync/SavedSitesSyncDataProviderTest.kt
  app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesDeduplicationPersisterTest.kt
  app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesDuplicateFinderTest.kt
  app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesLocalWinsPersisterTest.kt
  app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesRemoteWinsPersisterTest.kt
  app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesTimestampPersisterTest.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/di/SavedSitesModule.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/Models.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/RealSyncSavedSitesRepository.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataProvider.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncPersister.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SyncSavedSitesRepository.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithm.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/store/SavedSitesSyncMetadataDao.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/store/SavedSitesSyncMetadataDatabase.kt
  saved-sites/saved-sites-impl/src/test/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithmTest.kt
Labels: STACKED PR - DO NOT MERGE

#3989 Sync: Improve lists mechanism - overwrite folders locally
  app/src/test/java/com/duckduckgo/app/bookmarks/model/SyncSavedSitesRepositoryTest.kt
  app/src/test/java/com/duckduckgo/app/sync/SavedSitesSyncDataProviderTest.kt
  app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesDeduplicationPersisterTest.kt
  app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesDuplicateFinderTest.kt
  app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesLocalWinsPersisterTest.kt
  app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesRemoteWinsPersisterTest.kt
  app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesTimestampPersisterTest.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/Models.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/RealSyncSavedSitesRepository.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataProvider.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncPersister.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SyncSavedSitesRepository.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesDeduplicationPersister.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesLocalWinsPersister.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesRemoteWinsPersister.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithm.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterStrategy.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesTimestampPersister.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/store/SavedSitesSyncMetadataDao.kt
  saved-sites/saved-sites-impl/src/test/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithmTest.kt
  saved-sites/saved-sites-store/src/main/java/com/duckduckgo/savedsites/store/SavedSitesRelationsDao.kt
Labels: STACKED PR - DO NOT MERGE

#4017 Update content scope scripts to version 4.56.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4022 Add additional configChanges to stop Activities being destroyed when bluetooth keyboard (dis)connects
  app/src/main/AndroidManifest.xml
  autofill/autofill-impl/src/main/AndroidManifest.xml
Labels: QA-Optional

#4014 Get translations for updated autofill terminology, preferring passwords over logins
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/donottranslate.xml
  app/src/main/res/values/strings.xml
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Labels: QA-Optional

#3964 Sync: Improve lists mechanism - Metadata
  app/src/test/java/com/duckduckgo/app/bookmarks/BookmarkTestUtils.kt
  app/src/test/java/com/duckduckgo/app/bookmarks/model/SavedSitesRepositoryTest.kt
  app/src/test/java/com/duckduckgo/app/bookmarks/model/SyncSavedSitesRepositoryTest.kt
  app/src/test/java/com/duckduckgo/app/sync/SavedSitesSyncDataProviderTest.kt
  app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesDeduplicationPersisterTest.kt
  app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesDuplicateFinderTest.kt
  app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesLocalWinsPersisterTest.kt
  app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesRemoteWinsPersisterTest.kt
  app/src/test/java/com/duckduckgo/app/sync/algorithm/SavedSitesTimestampPersisterTest.kt
  saved-sites/saved-sites-api/src/main/java/com/duckduckgo/savedsites/api/SavedSitesRepository.kt
  saved-sites/saved-sites-impl/build.gradle
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/FavoritesDelegate.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/SavedSitesRepository.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/di/SavedSitesModule.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/Models.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/RealSyncSavedSitesRepository.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataProvider.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncPersister.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SyncSavedSitesRepository.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesDeduplicationPersister.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesDuplicateFinder.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesLocalWinsPersister.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesRemoteWinsPersister.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithm.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterStrategy.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesTimestampPersister.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/store/SavedSitesSyncMetadataDao.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/store/SavedSitesSyncMetadataDatabase.kt
  saved-sites/saved-sites-impl/src/test/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncPersisterTest.kt
  saved-sites/saved-sites-impl/src/test/java/com/duckduckgo/savedsites/impl/sync/algorithm/SavedSitesSyncPersisterAlgorithmTest.kt
  saved-sites/saved-sites-store/src/main/java/com/duckduckgo/savedsites/store/SavedSitesEntitiesDao.kt
  saved-sites/saved-sites-store/src/main/java/com/duckduckgo/savedsites/store/SavedSitesRelationsDao.kt
Labels: STACKED PR - DO NOT MERGE

#3998 Never save passwords for this site: api and storage
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/securestorage/RealSecureStorageRepositoryFactory.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/securestorage/SecureStorage.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/store/NeverSavedSiteRepository.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStoreTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/store/RealNeverSavedSiteRepositoryTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/FakeSecureStorage.kt
  autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
  autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
  autofill/autofill-internal/src/main/res/values/donottranslate.xml
  autofill/autofill-store/build.gradle
  autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/SecureStorageRepository.kt
  autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/db/NeverSavedSiteEntity.kt
  autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/db/NeverSavedSitesDao.kt
  autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/db/SecureStorageDatabase.kt
  autofill/autofill-store/src/test/java/com.duckduckgo.autofill.store/RealSecureStorageRepositoryTest.kt
Labels: STACKED PR - DO NOT MERGE

#3999 Never save passwords for this site: Update Save Dialog UX and Password Management Screen
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/AutofillJavascriptInterface.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/RealDuckAddressLoginCreator.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/configuration/AutofillRuntimeConfigProvider.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/neversaved/NeverSavedSitesViewState.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/AutofillSavingCredentialsDialogFragment.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/AutofillSavingCredentialsViewModel.kt
  autofill/autofill-impl/src/main/res/layout/content_autofill_save_new_credentials.xml
  autofill/autofill-impl/src/main/res/menu/autofill_list_mode_menu.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/AutofillStoredBackJavascriptInterfaceTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/RealDuckAddressLoginCreatorTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/configuration/RealAutofillRuntimeConfigProviderTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/saving/AutofillSavingCredentialsViewModelTest.kt
Labels: STACKED PR - DO NOT MERGE

#4038 Update reference tests to version 1703196979
  package-lock.json
  package.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/amplinks/config_reference.json
Labels: reference tests, automated pr

#4043 Fix compilation error by making TestSharedPrefsProvider override getEncryptedSharedPrefs
  sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/SyncRemoteFeatureToggleTest.kt
Labels: QA-Optional

#4042 Improve validation on the data received from autofill JS functions
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/AutofillJavascriptInterface.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/jsbridge/request/AutofillRequestParser.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/AutofillStoredBackJavascriptInterfaceTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/jsbridge/request/AutofillJsonRequestParserTest.kt
Labels: QA-Optional

#4028 Update autofill enabled toggle's subtitle to remove trailing period
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Labels: QA-Optional
