Repository duckduckgo/Android, pull requests merged in 2023-07, with the labels that each got.

#3293 Update content scope scripts to latest version
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3295 Sync: DataObserver should not be triggered when sync in progress
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SavedSitesSyncDataObserver.kt
Labels: QA-Optional

#3287 New pixels for the Settings screen and additional screens launched from Settings
  app/src/main/java/com/duckduckgo/app/about/AboutDuckDuckGoViewModel.kt
  app/src/main/java/com/duckduckgo/app/permissionsandprivacy/PermissionsAndPrivacyViewModel.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
  app/src/test/java/com/duckduckgo/app/about/AboutDuckDuckGoViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/permissionsandprivacy/PermissionsAndPrivacyViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
Labels: STACKED PR - DO NOT MERGE

#3280 Add the updated copy + translations
  app/src/main/java/com/duckduckgo/app/about/AboutDuckDuckGoViewModel.kt
  app/src/main/java/com/duckduckgo/app/permissionsandprivacy/PermissionsAndPrivacyViewModel.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/donottranslate.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/duckduckgo/app/about/AboutDuckDuckGoViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/permissionsandprivacy/PermissionsAndPrivacyViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
Labels: STACKED PR - DO NOT MERGE

#3332 Follow up: Remove ATB info from AppTP pixels + 2 new(-ish) pixels + other AppTP pixels
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixelNames.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/DeviceShieldPixels.kt
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/pixels/RealDeviceShieldPixelsTest.kt
  app/src/main/java/com/duckduckgo/app/global/api/AtpPixelRemovalInterceptor.kt
  app/src/test/java/com/duckduckgo/app/global/api/AtpPixelRemovalInterceptorTest.kt
Labels: QA-Optional

#3342 Add query parameter UI tests
  .maestro/privacy_tests/10_-_Query_Parameters,_utm_source_and_1_standard_parameter.yaml
  .maestro/privacy_tests/11_-_Query_Parameters,_utm_source_and_utm_medium.yaml
  .maestro/privacy_tests/12_-_Query_Parameters,_fbclid,_fb_source_and_1_standard_parameter.yaml
  .maestro/privacy_tests/13_-_Query_Parameters,_link_which_should_not_be_rewritten.yaml
Labels: QA-Optional

#3343 Update API level testing expectations in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: QA-Optional

#3340 Update reference tests to version 1689232034
  package-lock.json
  package.json
Labels: reference tests, automated pr

#3341 Update content scope scripts to version 4.26.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3354 Removed unneeded calls to isAddToHomeSupported().
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
Labels: QA-Optional

#3351 Add public API docs
  .github/workflows/docs.yml
  build.gradle
Labels: QA-Optional

#3356 Default browser - Address the usage of deprecated resolveActivity
  app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserDetector.kt
Labels: QA-Optional

#3364 Update content scope scripts to version 4.27.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3363 Update reference tests to version 1689778581
  package-lock.json
  package.json
Labels: reference tests, automated pr

#3349 Translations for managing duck addresses
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Labels: QA-Optional

#3371 Update reference tests to version 1689858388
  package-lock.json
  package.json
Labels: reference tests, automated pr

#3374 Update reference tests to version 1689964986
  app/src/test/resources/reference_tests/brokensites/tests.json
  package-lock.json
  package.json
Labels: reference tests, automated pr

#3375 Update content scope scripts to version 4.27.1
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3386 Move SecureStoreBackedAutofillStore to autofill-impl module
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStore.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/di/AutofillModule.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStoreTest.kt
Labels: QA-Optional

#3390 Update content scope scripts to version 4.29.0
  node_modules/@duckduckgo/content-scope-scripts/README.md
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts
