Repository duckduckgo/Android, pull requests merged in 2023-10, with the labels that each got.

#3617 GHA: Remove external contributor step
  .github/workflows/action-pr-opened.yaml
Labels: QA-Optional

#3629 Update content scope scripts to version 4.38.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3623 Disable no engagement notifications experiment
  app/src/main/java/com/duckduckgo/app/di/NotificationModule.kt
  app/src/main/java/com/duckduckgo/app/notification/AndroidNotificationScheduler.kt
  app/src/test/java/com/duckduckgo/app/notification/AndroidSchedulerNotificationTest.kt
  app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
  statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Labels: QA-Optional

#3647 Update content scope scripts to version 4.39.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3620 Remove set-as-default dialog from experiment notification
  app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserObserver.kt
  app/src/main/java/com/duckduckgo/app/global/install/AppInstallStore.kt
  app/src/main/java/com/duckduckgo/app/notification/NotificationRegistrar.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/main/java/com/duckduckgo/app/settings/SettingsActivity.kt
  app/src/main/java/com/duckduckgo/app/settings/SettingsViewModel.kt
  app/src/main/res/values/donottranslate.xml
  app/src/test/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserObserverTest.kt
  app/src/test/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt
Labels: QA-Optional

#3666 Add readme for installation module
  installation/installation-impl/src/main/java/com/duckduckgo/installation/impl/installer/InstallSourceExtractor.kt
  installation/installation-impl/src/main/java/com/duckduckgo/installation/impl/installer/InstallSourceLifecycleObserver.kt
  installation/installation-impl/src/test/java/InstallSourceLifecycleObserverTest.kt
  installation/readme.md
Labels: QA-Optional

#3685 Force reset config
  privacy-config/privacy-config-store/src/main/java/com/duckduckgo/privacy/config/store/PrivacyConfigDatabase.kt
Labels: QA-Optional

#3679 Add web compat readme
  web-compat/readme.md
Labels: QA-Optional

#3675 Add Content Scope Scripts readme
  content-scope-scripts/readme.md
Labels: QA-Optional

#3676 Add fingerprint protection readme
  fingerprint-protection/readme.md
Labels: QA-Optional

#3677 Add element hiding readme
  element-hiding/readme.md
Labels: QA-Optional

#3678 Add runtime checks readme
  runtime-checks/readme.md
Labels: QA-Optional

#3700 Fix crash when changing locale
  app/src/main/java/com/duckduckgo/widget/VoiceSearchWidgetUpdaterReceiver.kt
  voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/ActivityResultLauncherWrapper.kt
  voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/PermissionAwareVoiceSearchLauncher.kt
  voice-search/voice-search-impl/src/test/java/com/duckduckgo/voice/impl/PermissionAwareVoiceSearchLauncherTest.kt
Labels: STACKED PR - DO NOT MERGE

#3699 Fix favorites not triggered when focusing site
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/widget/VoiceSearchWidgetUpdaterReceiver.kt
  voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/ActivityResultLauncherWrapper.kt
  voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/PermissionAwareVoiceSearchLauncher.kt
  voice-search/voice-search-impl/src/test/java/com/duckduckgo/voice/impl/PermissionAwareVoiceSearchLauncherTest.kt
Labels: STACKED PR - DO NOT MERGE

#3709 Add readme for secure-storage modules
  secure-storage/readme.md
Labels: QA-Optional

#3717 Update content scope scripts to version 4.40.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3686 Fix disabled state in Restore Protected Apps
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionExclusionListActivity.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedFragment.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModel.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/TrackerFeedAdapter.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/TrackerDividerItemDecoration.kt
  app-tracking-protection/vpn-impl/src/main/res/layout/activity_device_shield_activity.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_activity_entry.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_excluded_app_entry_skeleton.xml
Labels: STACKED PR - DO NOT MERGE

#3684 Fix touch feedback in AppTP onboarding
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/apps/ui/TrackingProtectionExclusionListActivity.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedFragment.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldActivityFeedViewModel.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/DeviceShieldTrackerActivity.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/TrackerFeedAdapter.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/tracker_activity/view/TrackerDividerItemDecoration.kt
  app-tracking-protection/vpn-impl/src/main/res/layout/activity_device_shield_activity.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/activity_vpn_onboarding.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_activity_entry.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/view_device_shield_excluded_app_entry_skeleton.xml
Labels: STACKED PR - DO NOT MERGE

#3660 Add default browser experiment variants
  app/src/test/java/com/duckduckgo/app/statistics/VariantManagerTest.kt
  remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/AppRemoteMessagingRepository.kt
  remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/di/RemoteMessagingModule.kt
  remote-messaging/remote-messaging-impl/src/test/java/com/duckduckgo/remote/messaging/impl/AppRemoteMessagingRepositoryTest.kt
  statistics/src/main/java/com/duckduckgo/app/statistics/VariantManager.kt
Labels: DO NOT MERGE, QA-Optional

#3741 Update content scope scripts to version 4.41.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#3745 Update reference tests to version 1698156591
  package-lock.json
  package.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackerallowlist/tracker_allowlist_matching_tests.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackerallowlist/tracker_allowlist_reference.json
Labels: reference tests, automated pr

#3755 Translations for email protection in-context signup
  app/src/main/res/values-ru/strings.xml
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Labels: QA-Optional

#3766 Translations for updated About screen
  app/src/main/java/com/duckduckgo/app/about/AboutDuckDuckGoActivity.kt
  app/src/main/res/layout/content_about_duck_duck_go.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/donottranslate.xml
  app/src/main/res/values/strings.xml
Labels: QA-Optional

#3726 Update About screen copy
  app/src/main/java/com/duckduckgo/app/about/AboutDuckDuckGoActivity.kt
  app/src/main/java/com/duckduckgo/app/about/AboutDuckDuckGoViewModel.kt
  app/src/main/res/layout/content_about_duck_duck_go.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
Labels: STACKED PR - DO NOT MERGE
