Repository duckduckgo/Android, pull requests merged in 2024-07, with the labels that each got.

#4702 Update content scope scripts to version 5.25.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4708 Cleanup library dependency file, remove unusued declarations
  versions.properties
Labels: QA-Optional

#4710 Catch HitTestResult NullPointerException
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Labels: QA-Optional

#4713 Hotfix/5.207.1
  app/build.gradle
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/NewStateKillSwitch.kt
  app/src/main/java/com/duckduckgo/app/browser/WebNavigationState.kt
  app/src/test/java/com/duckduckgo/app/browser/WebNavigationStateComparisonTest.kt
  app/version/version.properties
Labels: HOTFIX DO NOT MERGE

#4715 Remove not-auto-renewable from ACTIVE mapping
  subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProSubscriptionStatusMatchingAttribute.kt
  subscriptions/subscriptions-impl/src/test/java/com/duckduckgo/subscriptions/impl/rmf/RMFPProSubscriptionStatusMatchingAttributeTest.kt
Labels: QA-Optional

#4706 Show host in download confirmation dialog
  downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/DownloadConfirmationFragment.kt
  downloads/downloads-impl/src/main/res/layout/download_confirmation.xml
  downloads/downloads-impl/src/main/res/values-bg/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-cs/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-da/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-de/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-el/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-es/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-et/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-fi/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-fr/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-hr/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-hu/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-it/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-lt/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-lv/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-nb/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-nl/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-pl/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-pt/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-ro/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-ru/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-sk/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-sl/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-sv/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values-tr/strings-downloads.xml
  downloads/downloads-impl/src/main/res/values/strings-downloads.xml
Labels: DO NOT MERGE

#4721 Update dependency: Robolectric. From 4.11.1 to 4.12.2
  downloads/downloads-impl/src/test/java/com/duckduckgo/downloads/impl/DataUriParserTest.kt
  downloads/downloads-impl/src/test/java/com/duckduckgo/downloads/impl/DownloaderUtilTest.kt
  downloads/downloads-impl/src/test/java/com/duckduckgo/downloads/impl/UriUtilsFilenameExtractorTest.kt
  versions.properties
Labels: QA-Optional

#4723 Add support for specifying a custom debug signing certificate
  app/build.gradle
Labels: QA-Optional

#4720 Fix ViewModels IllegalStateException
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Labels: QA-Optional

#4718 Apply autofill translations for deleting all passwords
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Labels: QA-Optional

#4736 Update content scope scripts to version 6.0.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4733 Android: Add pixels to understand navigation and search entry points
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/EngagementPixelsParamRemovalPlugin.kt
  app/src/main/java/com/duckduckgo/app/browser/newtab/FocusedLegacyViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageViewModel.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt
  app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherActivity.kt
  app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherAdapter.kt
  app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherListener.kt
  app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
  app/src/test/java/com/duckduckgo/app/browser/newtab/NewTabLegacyPageViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/systemsearch/SystemSearchViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/SavedSitesPixelName.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/SavedSitesPixelsParamRemovalPlugin.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/bookmarks/BookmarkScreenViewHolders.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/bookmarks/BookmarksViewModel.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/dialogs/EditBookmarkFolderDialogFragment.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/dialogs/EditSavedSiteDialogFragment.kt
  saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/dialogs/SavedSiteDialogFragment.kt
  saved-sites/saved-sites-impl/src/test/java/com/duckduckgo/savedsites/impl/bookmarks/BookmarksViewModelTest.kt
Labels: QA-Optional

#4749 Update reference tests to version 1720621685
  app/src/test/resources/reference_tests/brokensites/tests.json
  package-lock.json
  package.json
Labels: reference tests, automated pr

#4758 Update fastlane to allow for updating release notes of an existing release in Play Store
  fastlane/Fastfile
  fastlane/README.md
Labels: QA-Optional

#4754 Update Anvil to 2.5.0-beta09
  build.gradle
Labels: QA-Optional

#4729 Translations for autofill import via desktop sync
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Labels: QA-Optional

#4767 Ignore FingerprintProtectionTest property order
  app/src/androidTest/java/com/duckduckgo/espresso/privacy/FingerprintProtectionTest.kt
Labels: QA-Optional

#4766 Update content scope scripts to version 6.2.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4771 Add fastlane lane for updating GitHub release notes (using `gh`)
  fastlane/Fastfile
  fastlane/README.md
Labels: QA-Optional

#4770 Update content scope scripts to version 6.3.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4769 Update reference tests to version 1721137609
  app/src/test/resources/reference_tests/brokensites/tests.json
  package-lock.json
  package.json
Labels: reference tests, automated pr

#4777 Rearranging tabs: Unit tests
  app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
  app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/userstate/UserStateReporterTest.kt
Labels: QA-Optional

#4740 Feature flag for autofill site breakage reporting
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/reporting/AutofillSiteBreakageReportingDataStore.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/reporting/remoteconfig/AutofillSiteBreakageReportingExceptionsPersister.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/reporting/remoteconfig/AutofillSiteBreakageReportingFeature.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/reporting/remoteconfig/AutofillSiteBreakageReportingModule.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/reporting/remoteconfig/AutofillSiteBreakageReportingRemoteSettingsPersister.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/reporting/remoteconfig/AutofillSiteBreakageReportingRemoteSettingsPersisterTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/feature/toggles/api/toggle/AutofillTestFeature.kt
  autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/reporting/AutofillSiteBreakageExceptionDatabase.kt
  autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/reporting/AutofillSiteBreakageReportingFeatureRepository.kt
Labels: QA-Optional

#4782 Add dev settings for clearing breakage reports for easier testing
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/reporting/AutofillSiteBreakageReportingDataStore.kt
  autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
  autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
  autofill/autofill-internal/src/main/res/values/donottranslate.xml
Labels: QA-Optional

#4797 Update content scope scripts to version 6.4.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4805 Update content scope scripts to version 6.5.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4811 Rename General settings pixel
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
Labels: QA-Optional

#4800 Fix Settings copy inconsistencies
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Labels: QA-Optional

#4798 Trigger translations for autofill breakage reporting
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Labels: QA-Optional

#4814 Android: Crash in BrowserWebViewClient.shouldOverride
  app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
Labels: QA-Optional

#4816 Fix onFireDialogVisibilityChanged crash
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Labels: QA-Optional

#4817 Fix RadioListAlertDialogBuilder BadTokenException
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/breakage/ReportBreakageCategorySingleChoiceActivity.kt
Labels: QA-Optional
