Repository duckduckgo/Android, pull requests merged in 2024-04, with the labels that each got.

#4398 Update content scope scripts to version 5.9.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4411 Update content scope scripts to version 5.10.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4425 Update content scope scripts to version 5.11.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4346 Expand bookmarks bottom sheet
  app/src/main/java/com/duckduckgo/app/bookmarks/ui/BookmarksBottomSheetDialog.kt
  app/src/main/res/drawable/rounded_top_corners_bottom_sheet_drawable.xml
  app/src/main/res/layout/bottom_sheet_add_bookmark.xml
Labels: QA-Optional

#4429 Update content scope scripts to version 5.12.0
  node_modules/@duckduckgo/privacy-dashboard/build/app/public/js/base.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4428 Catch exceptions when launching external app
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Labels: QA-Optional

#4443 Improve voice search compatibility
  common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/LocaleExtensions.kt
  common/common-utils/src/test/java/com/duckduckgo/common/utils/extensions/LocaleExtensionsTest.kt
  statistics/src/main/java/com/duckduckgo/app/statistics/pixels/FeatureRetentionPixelSender.kt
  voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/VoiceSearchAvailabilityConfig.kt
Labels: QA-Optional

#4431 Update Privacy Dashboard to 3.5.0
  package-lock.json
Labels: QA-Optional

#4453 Update content scope scripts to version 5.13.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4464 Ensure addDocumentStartJavaScript is called on main thread
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/InlineBrowserAutofill.kt
Labels: QA-Optional

#4441 Translations for warning message in passwords screen when webview too old
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Labels: QA-Optional

#4461 Android: Permissions issue in Custom Tab
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/customtabs/CustomTabActivity.kt
Labels: QA-Optional

#4477 Rename SyncAttributeMatcherPlugin
  voice-search/voice-search-impl/src/main/java/com/duckduckgo/voice/impl/rmf/VoiceSearchAttributeMatcher.kt
Labels: QA-Optional

#4420 Defer local results until remote ones are available
  app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoComplete.kt
Labels: STACKED PR - DO NOT MERGE

#4362 Store history
  app/build.gradle
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
  app/src/androidTest/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandlerTest.kt
  app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoComplete.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
  app/src/main/java/com/duckduckgo/app/browser/autocomplete/BrowserAutoCompleteSuggestionsAdapter.kt
  app/src/main/java/com/duckduckgo/app/browser/autocomplete/SuggestionViewHolderFactory.kt
  app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandler.kt
  app/src/test/java/com/duckduckgo/app/autocomplete/api/AutoCompleteApiTest.kt
  common/common-utils/src/main/java/com/duckduckgo/common/utils/CurrentTimeProvider.kt
  history/history-api/.gitignore
  history/history-api/build.gradle
  history/history-api/src/main/java/com/duckduckgo/history/api/HistoryEntry.kt
  history/history-api/src/main/java/com/duckduckgo/history/api/NavigationHistory.kt
  history/history-impl/build.gradle
  history/history-impl/lint-baseline.xml
  history/history-impl/src/main/java/com/duckduckgo/history/impl/HistoryEntry.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/HistoryModule.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/HistoryRepository.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/RealNavigationHistory.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/store/HistoryDao.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/store/HistoryDatabase.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/store/HistoryEntryEntity.kt
  history/history-impl/src/test/java/com/duckduckgo/history/impl/HistoryTest.kt
  history/history-impl/src/test/java/com/duckduckgo/history/impl/store/HistoryDaoTest.kt
  history/readme.md
Labels: STACKED PR - DO NOT MERGE

#4357 Add pixels for autocomplete
  app/build.gradle
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
  app/src/androidTest/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandlerTest.kt
  app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoComplete.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
  app/src/main/java/com/duckduckgo/app/browser/autocomplete/BrowserAutoCompleteSuggestionsAdapter.kt
  app/src/main/java/com/duckduckgo/app/browser/autocomplete/SuggestionViewHolderFactory.kt
  app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandler.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/test/java/com/duckduckgo/app/autocomplete/api/AutoCompleteApiTest.kt
  common/common-utils/src/main/java/com/duckduckgo/common/utils/CurrentTimeProvider.kt
  history/history-api/.gitignore
  history/history-api/build.gradle
  history/history-api/src/main/java/com/duckduckgo/history/api/HistoryEntry.kt
  history/history-api/src/main/java/com/duckduckgo/history/api/NavigationHistory.kt
  history/history-impl/build.gradle
  history/history-impl/lint-baseline.xml
  history/history-impl/src/main/java/com/duckduckgo/history/impl/HistoryEntry.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/HistoryModule.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/HistoryRepository.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/RealNavigationHistory.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/store/HistoryDao.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/store/HistoryDatabase.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/store/HistoryEntryEntity.kt
  history/history-impl/src/test/java/com/duckduckgo/history/impl/HistoryTest.kt
  history/history-impl/src/test/java/com/duckduckgo/history/impl/store/HistoryDaoTest.kt
  history/readme.md
  statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Labels: STACKED PR - DO NOT MERGE

#4349 Add support for bottom section
  app/build.gradle
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
  app/src/androidTest/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandlerTest.kt
  app/src/main/java/com/duckduckgo/app/autocomplete/api/AutoComplete.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
  app/src/main/java/com/duckduckgo/app/browser/autocomplete/BrowserAutoCompleteSuggestionsAdapter.kt
  app/src/main/java/com/duckduckgo/app/browser/autocomplete/SuggestionViewHolderFactory.kt
  app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandler.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/test/java/com/duckduckgo/app/autocomplete/api/AutoCompleteApiTest.kt
  common/common-utils/src/main/java/com/duckduckgo/common/utils/CurrentTimeProvider.kt
  history/history-api/.gitignore
  history/history-api/build.gradle
  history/history-api/src/main/java/com/duckduckgo/history/api/HistoryEntry.kt
  history/history-api/src/main/java/com/duckduckgo/history/api/NavigationHistory.kt
  history/history-impl/build.gradle
  history/history-impl/lint-baseline.xml
  history/history-impl/src/main/java/com/duckduckgo/history/impl/HistoryEntry.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/HistoryModule.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/HistoryRepository.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/RealNavigationHistory.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/store/HistoryDao.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/store/HistoryDatabase.kt
  history/history-impl/src/main/java/com/duckduckgo/history/impl/store/HistoryEntryEntity.kt
  history/history-impl/src/test/java/com/duckduckgo/history/impl/HistoryTest.kt
  history/history-impl/src/test/java/com/duckduckgo/history/impl/store/HistoryDaoTest.kt
  history/readme.md
  statistics/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Labels: STACKED PR - DO NOT MERGE
