Repository duckduckgo/Android, pull requests merged in 2024-10, with the labels that each got.

#5054 Remove aestheticUpdates Toggle
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/onboarding/ui/page/extendedonboarding/ExtendedOnboardingFeatureToggles.kt
Labels: QA-Optional

#5092 Ensure autofill nightly tests succeed
  .maestro/autofill/2_autofill_add_search_update_delete_creds.yaml
  .maestro/autofill/3_autofill_prompted_to_save_creds_on_form.yaml
  .maestro/autofill/steps/delete_logins.yaml
  .maestro/autofill/steps/manual_update.yaml
Labels: QA-Optional

#5108 Use safeWebMessageHandler code for autofill integration
  app/src/main/java/com/duckduckgo/app/browser/DuckDuckGoWebView.kt
  app/src/main/java/com/duckduckgo/app/browser/RealWebViewCapabilityChecker.kt
  app/src/main/java/com/duckduckgo/app/browser/SafeWebMessageHandlerImpl.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/InlineBrowserAutofill.kt
  browser-api/build.gradle
  browser-api/src/main/java/com/duckduckgo/app/browser/api/SafeWebMessageHandler.kt
Labels: HOTFIX DO NOT MERGE

#5107 Correctly load intercepted URLs
  app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
Labels: QA-Optional

#5120 Rename duck-player pixel id to duckplayer
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerPixelName.kt
  duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
  duckplayer/duckplayer-impl/src/test/kotlin/com/duckduckgo/duckplayer/impl/RealDuckPlayerTest.kt
Labels: QA-Optional

#5106 Fix the missing last item in autocomplete list
  app/src/main/java/com/duckduckgo/app/browser/omnibar/LegacyOmnibarView.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/TopAppBarBehavior.kt
Labels: bug

#5119 Translations: Search Suggestion Update
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
Labels: QA-Optional

#5099 Omit autofill toggled pixel in certain conditions
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/engagement/store/AutofillEngagementRepository.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/engagement/store/DefaultAutofillEngagementRepositoryTest.kt
Labels: QA-Optional

#5137 Fix popup menu IllegalStateException
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Labels: QA-Optional

#5151 Update content scope scripts to version 6.22.0
  node_modules/@duckduckgo/content-scope-scripts/README.md
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/assets/img/cog.svg
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/assets/img/dax.svg
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/assets/img/eyeball.svg
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/assets/img/info-icon.svg
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/assets/img/open.svg
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/assets/img/player-bg.png
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/assets/player.css
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/messages.example.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/messages.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/utils.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5165 Bug: autocomplete pixels firing when Adding Bookmark
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchActivity.kt
  app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt
  app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
  app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
  browser-api/build.gradle
  browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
Labels: STACKED PR - DO NOT MERGE

#5155 Fix IllegalArgumentException when savedSiteAdded
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Labels: QA-Optional

#5186 Android: Remove pixels for Indonesia message
  app/src/main/java/com/duckduckgo/app/browser/indonesiamessage/IndonesiaNewTabSectionView.kt
  app/src/main/java/com/duckduckgo/app/browser/indonesiamessage/IndonesiaNewTabSectionViewModel.kt
  app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/test/java/com/duckduckgo/app/browser/indonesiamessage/IndonesiaNewTabSectionViewModelTest.kt
Labels: QA-Optional

#5177 Update content scope scripts to version 6.23.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.css
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5196 Update content scope scripts to version 6.24.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5210 Update content scope scripts to version 6.27.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.css
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5207 Fix RMF unique pixel: adding tag as part of unique type
  remote-messaging/remote-messaging-impl/src/main/java/com/duckduckgo/remote/messaging/impl/pixels/RemoteMessagingPixels.kt
Labels: QA-Optional

#5089 Update tagline
  app/src/main/res/layout/include_system_search_onboarding.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
Labels: QA-Optional
