Repository duckduckgo/Android, pull requests merged in 2024-06, with the labels that each got.

#4607 Onboarding maestro tests updated
  .maestro/ad_click_detection_flows/10_-_m.js_bing-provided;_ad_domain_provided_but_incorrect_(dsl_not_needed).yaml
  .maestro/ad_click_detection_flows/11_-_y.js_bing-provided;_ad_domain_provided_but_it's_not_a_domain_(i.e.,_abcedf)_(u3_not_needed).yaml
  .maestro/ad_click_detection_flows/12_-_m.js_bing-provided;_ad_domain_provided_but_it's_not_a_domain_(i.e.,_abcedf)__(dsl_not_needed).yaml
  .maestro/ad_click_detection_flows/13_-_y.js_bing-provided;_ad_domain_provided_but_it's_a_subdomain_of_advertiser_(i.e.,_foo.www.search-company-site)_(u3_not_needed).yaml
  .maestro/ad_click_detection_flows/14_-_m.js_bing-provided;_ad_domain_provided_but_it's_a_subdomain_of_advertiser_(i.e.,_foo.www.search-company-site)__(dsl_not_needed).yaml
  .maestro/ad_click_detection_flows/1_-_y.js_heuristic;_no_ad_domain_param;_u3_param_included.yaml
  .maestro/ad_click_detection_flows/2_-_m.js_heuristic;_no_ad_domain_param;_dsl_param_included.yaml
  .maestro/ad_click_detection_flows/3_-_y.js_heuristic;_no_ad_domain_param,_but_missing_u3_param.yaml
  .maestro/ad_click_detection_flows/4_-_m.js_heuristic;_no_ad_domain_param,_but_missing_dsl_param.yaml
  .maestro/ad_click_detection_flows/5_-_y.js_heuristic;_ad_domain_provided,_but_empty_(u3_not_needed).yaml
  .maestro/ad_click_detection_flows/6_-_m.js_heuristic;_ad_domain_provided,_but_empty_(dsl_not_needed).yaml
  .maestro/ad_click_detection_flows/7_-_y.js_bing-provided;_ad_domain_provided_(u3_not_needed).yaml
  .maestro/ad_click_detection_flows/8_-_m.js_bing-provided;_ad_domain_provided_(dsl_not_needed).yaml
  .maestro/ad_click_detection_flows/9_-_y.js_bing-provided;_ad_domain_provided_but_incorrect_(u3_not_needed).yaml
  .maestro/ads_preview_flows/1-_design-system-components.yaml
  .maestro/custom_tabs/custom_tabs_navigation.yaml
  .maestro/custom_tabs/custom_tabs_navigation_new_tab.yaml
  .maestro/fire_button/fire_during_onboarding.yaml
  .maestro/notifications_permissions_android13_plus/1_-_permissions_allowed.yaml
  .maestro/notifications_permissions_android13_plus/2_-_permissions_denied.yaml
  .maestro/privacy_tests/10_-_Query_Parameters,_utm_source_and_1_standard_parameter.yaml
  .maestro/privacy_tests/11_-_Query_Parameters,_utm_source_and_utm_medium.yaml
  .maestro/privacy_tests/12_-_Query_Parameters,_fbclid,_fb_source_and_1_standard_parameter.yaml
  .maestro/privacy_tests/13_-_Query_Parameters,_link_which_should_not_be_rewritten.yaml
  .maestro/privacy_tests/1_-_Single-site,_single-tab,_session.yaml
  .maestro/privacy_tests/2_-_Single-site,_new-tab,_session.yaml
  .maestro/privacy_tests/3_-_Single-site,_new-tab,_session_variant_two.yaml
  .maestro/privacy_tests/4_-_Single-site,_multi-tab_session.yaml
  .maestro/privacy_tests/5_-_Multi-site,_single-tab,_session.yaml
  .maestro/privacy_tests/6_-_Multi-tab.yaml
  .maestro/privacy_tests/7_-_Browser_restart_mid-session.yaml
  .maestro/privacy_tests/8_-_Navigation_with_back_forward.yaml
  .maestro/privacy_tests/9_-_Navigation_with_refresh.yaml
  .maestro/security_tests/2_-_AddressBarSpoof,_aboutblank.yaml
  .maestro/shared/onboarding.yaml
  .maestro/tabs/open_multiple_tabs.yaml
Labels: QA-Optional

#4611 Update content scope scripts to version 5.19.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4615 Delete unused onboarding strings
  app/lint-baseline.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
Labels: QA-Optional

#4627 Add excluded system apps in breakage metadata
  network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/exclusion/systemapps/SystemAppsExclusionRepository.kt
  network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/integration/NetPStateCollector.kt
Labels: QA-Optional

#4623 Add WebView version check to no-op WebMessageListener
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/StringExtensions.kt
  common/common-utils/src/test/java/com/duckduckgo/common/utils/extensions/StringExtensionsTest.kt
Labels: QA-Optional

#4640 Android: Incorrect exemption check
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickManager.kt
  ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickManagerTest.kt
Labels: QA-Optional

#4630 Settings: Remove BETA label for Desktop settings
  app/src/main/res/layout/content_settings_other.xml
Labels: QA-Optional

#4645 Implement m.pageloads.with.ad.attribution.android
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickData.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickManager.kt
  ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickManagerTest.kt
  app/src/main/java/com/duckduckgo/app/global/api/PixelAdClickAttributionRemovalInterceptor.kt
Labels: QA-Optional

#4655 Update content scope scripts to version 5.21.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4660 java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState - CustomTabActivity
  app/src/main/java/com/duckduckgo/app/browser/customtabs/CustomTabActivity.kt
Labels: QA-Optional

#4675 Android Crash: com.duckduckgo.adclick.impl.DuckDuckGoAdClickData.getExemption
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickData.kt
Labels: QA-Optional

#4674 Fix CustomTab crash/anr attribution
  app/src/main/java/com/duckduckgo/app/browser/customtabs/CustomTabActivity.kt
Labels: QA-Optional

#4682 Delete dummy WebMessageListener
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/webview/DummyWebMessageListenerFeature.kt
Labels: QA-Optional

#4680 Fix IllegalStateException on addOrReplaceNewTab
  app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
Labels: QA-Optional

#4685 Remove temporary DMA legacy pixels
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/play/java/com/duckduckgo/referral/PlayStoreAppReferrerStateListener.kt
Labels: QA-Optional

#4690 Fix webViewContainer UninitializedPropertyAccessException
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Labels: QA-Optional

#4689 Update content scope scripts to version 5.22.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4699 Left-align text in individual overflow menus in password manager
  autofill/autofill-impl/src/main/res/layout/overflow_menu_list_item.xml
Labels: QA-Optional

#4693 Update content scope scripts to version 5.23.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4696 Update autocomplete settings strings and mark them as untranslated
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
Labels: QA-Optional, Pending Translations
