Repository duckduckgo/Android, pull requests merged in 2024-08, with the labels that each got.

#4841 Autofill: adds internal setting to reset decline counter
  autofill/autofill-internal/build.gradle
  autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
  autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
  autofill/autofill-internal/src/main/res/values/donottranslate.xml
  autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/AutofillPrefsStore.kt
Labels: QA-Optional

#4856 Update snackbar duration for telling users autofill can be changed in settings
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/saving/ResultHandlerPromptToDisableCredentialSaving.kt
Labels: QA-Optional

#4853 Autofill: save onboarding translations
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Labels: QA-Optional

#4842 List mode: Tests
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
Labels: QA-Optional

#4867 Update content scope scripts to version 6.6.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4827 Bump Privacy Dashboard to 5.0.0
  node_modules/@duckduckgo/privacy-dashboard/build/app/html/android.html
  node_modules/@duckduckgo/privacy-dashboard/build/app/html/browser.html
  node_modules/@duckduckgo/privacy-dashboard/build/app/html/ios.html
  node_modules/@duckduckgo/privacy-dashboard/build/app/html/macos.html
  node_modules/@duckduckgo/privacy-dashboard/build/app/html/popup.html
  node_modules/@duckduckgo/privacy-dashboard/build/app/html/windows.html
  node_modules/@duckduckgo/privacy-dashboard/build/app/img/refresh-assets/chat-private-128.svg
  node_modules/@duckduckgo/privacy-dashboard/build/app/img/refresh-assets/switch-shield-128.svg
  node_modules/@duckduckgo/privacy-dashboard/build/app/public/css/base.css
  node_modules/@duckduckgo/privacy-dashboard/build/app/public/css/popup.css
  node_modules/@duckduckgo/privacy-dashboard/build/app/public/js/base.js
  package-lock.json
  package.json
Labels: BLOCKED: DO NOT MERGE

#4862 Translations for recent item removal
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
Labels: QA-Optional

#4904 Update content scope scripts to version 6.8.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4920 Update content scope scripts to version 6.9.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4906 Add the feature flag to switch off the new implementation
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickData.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/di/AdClickModule.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/remoteconfig/AdClickAttributionFeature.kt
  ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickDataTest.kt
  app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
Labels: STACKED PR - DO NOT MERGE

#4905 Keep exemptions in case of closing a tab and subsequently undoing the action
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickData.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/di/AdClickModule.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/remoteconfig/AdClickAttributionFeature.kt
  ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickDataTest.kt
  app/src/androidTest/java/com/duckduckgo/app/tabs/db/TabsDaoTest.kt
  app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
  app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
  app/src/main/java/com/duckduckgo/app/tabs/db/TabsDbSanitizer.kt
  app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
  app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
  app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
  browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
Labels: STACKED PR - DO NOT MERGE

#4903 Clear the stored exemptions
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickData.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/di/AdClickModule.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/remoteconfig/AdClickAttributionFeature.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/store/exemptions/AdClickExemptionsDao.kt
  ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickDataTest.kt
  app/src/androidTest/java/com/duckduckgo/app/tabs/db/TabsDaoTest.kt
  app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
  app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
  app/src/main/java/com/duckduckgo/app/tabs/db/TabsDbSanitizer.kt
  app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
  app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
  app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
  browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
Labels: STACKED PR - DO NOT MERGE

#4899 Add the DB and store exemptions
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickData.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/di/AdClickModule.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/remoteconfig/AdClickAttributionFeature.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/store/exemptions/AdClickExemptionsDao.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/store/exemptions/AdClickExemptionsDatabase.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/store/exemptions/AdClickExemptionsEntities.kt
  ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickDataTest.kt
  app/src/androidTest/java/com/duckduckgo/app/tabs/db/TabsDaoTest.kt
  app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
  app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
  app/src/main/java/com/duckduckgo/app/tabs/db/TabsDbSanitizer.kt
  app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
  app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
  app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
  browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
Labels: STACKED PR - DO NOT MERGE

#4898 Feature branch for Persist Exemption on Android App Restart
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickData.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/di/AdClickModule.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/remoteconfig/AdClickAttributionFeature.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/store/exemptions/AdClickExemptionsDao.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/store/exemptions/AdClickExemptionsDatabase.kt
  ad-click/ad-click-impl/src/main/java/com/duckduckgo/adclick/impl/store/exemptions/AdClickExemptionsEntities.kt
  ad-click/ad-click-impl/src/test/java/com/duckduckgo/adclick/impl/DuckDuckGoAdClickDataTest.kt
  app/src/androidTest/java/com/duckduckgo/app/tabs/db/TabsDaoTest.kt
  app/src/androidTest/java/com/duckduckgo/app/tabs/model/TabDataRepositoryTest.kt
  app/src/main/java/com/duckduckgo/app/tabs/db/TabsDao.kt
  app/src/main/java/com/duckduckgo/app/tabs/db/TabsDbSanitizer.kt
  app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
  app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
  app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
  browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
Labels: STACKED PR - DO NOT MERGE

#4926 Add missing launch sources to autofill management screen
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
Labels: QA-Optional

#4894 Privacy Pro onboarding dialog translations
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
Labels: QA-Optional

#4934 Update reference tests to version 1724449523
  package-lock.json
  package.json
  privacy-config/privacy-config-impl/src/test/resources/reference_tests/trackingparameters/tests.json
Labels: reference tests, automated pr

#4935 Update content scope scripts to version 6.10.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4938 Add conflict strategy of ignore to stored crash hash keys
  anrs/anrs-store/src/main/java/com/duckduckgo/app/anrs/store/UncaughtExceptionDao.kt
Labels: QA-Optional

#4949 Fix FDroid build
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
  app/src/test/java/com/duckduckgo/app/cta/ui/OnboardingDaxDialogTests.kt
  subscriptions/subscriptions-api/src/main/java/com/duckduckgo/subscriptions/api/Subscriptions.kt
  subscriptions/subscriptions-dummy-impl/src/main/java/com/duckduckgo/subscriptions/impl/SubscriptionsDummy.kt
  subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
Labels: STACKED PR - DO NOT MERGE

#4959 Update content scope scripts to version 6.12.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4963 Updated maestro tests after persisting ad click exemptions.
  .maestro/privacy_tests/7_-_Browser_restart_mid-session.yaml
Labels: QA-Optional
