Repository duckduckgo/Android, pull requests merged in 2024-09, with the labels that each got.

#4972 Fix malformed JSON/XML
  app/src/main/res/layout/include_onboarding_view_dax_dialog.xml
  app/src/test/resources/json/parser_folders_and_favourites.json
Labels: QA-Optional

#4973 Use Timber instead of Log in DragLinearLayout
  new-tab-page/new-tab-page-impl/build.gradle
  new-tab-page/new-tab-page-impl/src/main/java/com/duckduckgo/newtabpage/impl/settings/DragLinearLayout.kt
Labels: QA-Optional

#4975 Rearranging tabs: Remove temporary pixels
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
  app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
Labels: QA-Optional

#4982 Update content scope scripts to version 6.14.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4991 Update content scope scripts to version 6.14.1
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4945 Omnibar position: Autocomplete
  app/src/main/java/com/duckduckgo/app/browser/menu/BrowserPopupMenu.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
Labels: STACKED PR - DO NOT MERGE

#4954 Omnibar position: Snackbar
  app/src/main/java/com/duckduckgo/app/browser/omnibar/BottomAppBarBehavior.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
  app/src/main/res/layout/include_omnibar_toolbar_bottom.xml
Labels: STACKED PR - DO NOT MERGE

#4997 Reduce the initial prod rollout percentage from 0.1% to 0.0001%
  fastlane/Fastfile
Labels: QA-Optional

#4994 Update content scope scripts to version 6.15.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5014 Fix survey's store declaration
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/survey/AutofillSurveyFeature.kt
Labels: QA-Optional

#5011 Omnibar Refactor: Extract LegacyOmnibar
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/LegacyOmnibarView.kt
  app/src/main/res/layout/fragment_browser_tab.xml
  app/src/main/res/layout/view_legacy_omnibar.xml
Labels: DO NOT MERGE

#5004 Translations: Highlights Onboarding Experiment
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
Labels: QA-Optional

#5027 Update content scope scripts to version 6.16.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5043 Disable C2 compiler in unit tests
  app/build.gradle
Labels: QA-Optional

#5040 Show on App Launch: Add pixels
  app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPlugin.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/model/ShowOnAppLaunchOption.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPluginTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModelTest.kt
  app/src/test/java/com/duckduckgo/fakes/FakePixel.kt
  statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Labels: STACKED PR - DO NOT MERGE

#5000 Show on App Launch: Add additional tests
  app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPlugin.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/model/ShowOnAppLaunchOption.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchOptionDataStore.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPluginTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/FakeShowOnAppLaunchOptionDataStore.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchPrefsDataStoreTest.kt
  app/src/test/java/com/duckduckgo/fakes/FakePixel.kt
  statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Labels: STACKED PR - DO NOT MERGE

#4995 Show on App Launch: Open launch option when set
  app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPlugin.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchUrlConverterImpl.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/UrlConverter.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/model/ShowOnAppLaunchOption.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchDataStoreModule.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchOptionDataStore.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
  app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPluginTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchUrlConverterImplTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/FakeShowOnAppLaunchOptionDataStore.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchPrefsDataStoreTest.kt
  app/src/test/java/com/duckduckgo/fakes/FakePixel.kt
  browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
  statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Labels: STACKED PR - DO NOT MERGE

#4952 Show on App Launch: Add persistence
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsActivity.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchActivity.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPlugin.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchUrlConverterImpl.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/UrlConverter.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/model/ShowOnAppLaunchOption.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchDataStoreModule.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchOptionDataStore.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
  app/src/main/res/layout/activity_general_settings.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPluginTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchUrlConverterImplTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/FakeShowOnAppLaunchOptionDataStore.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchPrefsDataStoreTest.kt
  app/src/test/java/com/duckduckgo/fakes/FakePixel.kt
  browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
  common/common-ui/src/main/java/com/duckduckgo/common/ui/view/listitem/RadioListItem.kt
  statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Labels: STACKED PR - DO NOT MERGE

#4950 Show on App Launch: Setting screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsActivity.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchActivity.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchScreens.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPlugin.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchUrlConverterImpl.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/UrlConverter.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/model/ShowOnAppLaunchOption.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchDataStoreModule.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchOptionDataStore.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
  app/src/main/res/layout/activity_general_settings.xml
  app/src/main/res/layout/activity_show_on_app_launch_setting.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPluginTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchUrlConverterImplTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/FakeShowOnAppLaunchOptionDataStore.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchPrefsDataStoreTest.kt
  app/src/test/java/com/duckduckgo/fakes/FakePixel.kt
  browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
  common/common-ui/src/main/java/com/duckduckgo/common/ui/view/listitem/RadioListItem.kt
  common/common-ui/src/main/java/com/duckduckgo/common/ui/view/text/DaxTextInput.kt
  common/common-ui/src/main/res/layout/view_radio_list_item.xml
  common/common-ui/src/main/res/values/attrs-radio-list-item.xml
  network-protection/network-protection-impl/src/main/res/layout/activity_netp_geoswitching.xml
  network-protection/network-protection-impl/src/main/res/layout/item_geoswitching_country.xml
  statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Labels: STACKED PR - DO NOT MERGE

#4946 Show on App Launch: General settings entry point
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsActivity.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchActivity.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchScreens.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPlugin.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchUrlConverterImpl.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModel.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/UrlConverter.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/model/ShowOnAppLaunchOption.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchDataStoreModule.kt
  app/src/main/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchOptionDataStore.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/main/java/com/duckduckgo/app/tabs/model/TabDataRepository.kt
  app/src/main/res/layout/activity_general_settings.xml
  app/src/main/res/layout/activity_show_on_app_launch_setting.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/GeneralSettingsViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchStateReporterPluginTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchUrlConverterImplTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/ShowOnAppLaunchViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/FakeShowOnAppLaunchOptionDataStore.kt
  app/src/test/java/com/duckduckgo/app/generalsettings/showonapplaunch/store/ShowOnAppLaunchPrefsDataStoreTest.kt
  app/src/test/java/com/duckduckgo/fakes/FakePixel.kt
  browser-api/src/main/java/com/duckduckgo/app/tabs/model/TabRepository.kt
  common/common-ui/src/main/java/com/duckduckgo/common/ui/view/listitem/RadioListItem.kt
  common/common-ui/src/main/java/com/duckduckgo/common/ui/view/text/DaxTextInput.kt
  common/common-ui/src/main/res/layout/view_radio_list_item.xml
  common/common-ui/src/main/res/values/attrs-radio-list-item.xml
  network-protection/network-protection-impl/src/main/res/layout/activity_netp_geoswitching.xml
  network-protection/network-protection-impl/src/main/res/layout/item_geoswitching_country.xml
  statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Labels: STACKED PR - DO NOT MERGE

#5024 List mode: Remove temporary pixel
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
  app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
Labels: QA-Optional

#5068 Update content scope scripts to version 6.19.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.css
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/js/index.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5078 Add autocomplete deletion daily pixel
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/main/java/com/duckduckgo/app/systemsearch/SystemSearchViewModel.kt
  app/src/test/java/com/duckduckgo/app/systemsearch/SystemSearchViewModelTest.kt
Labels: QA-Optional

#5075 Add feature flag for sending full installer package ID
  installation/installation-impl/build.gradle
  installation/installation-impl/src/main/java/com/duckduckgo/installation/impl/installer/di/InstallerModule.kt
  installation/installation-impl/src/main/java/com/duckduckgo/installation/impl/installer/fullpackage/InstallSourceFullPackageStore.kt
  installation/installation-impl/src/main/java/com/duckduckgo/installation/impl/installer/fullpackage/feature/InstallSourceFullPackageFeature.kt
  installation/installation-impl/src/main/java/com/duckduckgo/installation/impl/installer/fullpackage/feature/InstallSourceFullPackageListJsonParser.kt
  installation/installation-impl/src/test/java/com/duckduckgo/installation/impl/installer/fullpackage/IncludedPackagesTest.kt
  installation/installation-impl/src/test/java/com/duckduckgo/installation/impl/installer/fullpackage/InstallSourceFullPackageStoreImplTest.kt
  installation/installation-impl/src/test/java/com/duckduckgo/installation/impl/installer/fullpackage/feature/InstallSourceFullPackageListJsonParserImplTest.kt
  installation/installation-impl/src/test/resources/json/installerFullSource_emptyList.json
  installation/installation-impl/src/test/resources/json/installerFullSource_multipleEntryList.json
  installation/installation-impl/src/test/resources/json/installerFullSource_singleEntryList.json
Labels: QA-Optional
