Repository duckduckgo/Android, pull requests merged in 2024-01, with the labels that each got.

#4049 Update content scope scripts to version 4.58.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4053 Update content scope scripts to version 4.59.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4055 Fixed default browser.
  app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserDetector.kt
Labels: QA-Optional

#4059 Update to Anvil 2.4.9
  build.gradle
Labels: QA-Optional

#4050 Update gradle versions
  versions.properties
Labels: QA-Optional

#4079 Added images for F-Droid store listing.
  fastlane/metadata/android/en-US/images/featureGraphic.png
  fastlane/metadata/android/en-US/images/icon.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/1-Main.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/2-Search.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/3-Website.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/4-Email.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/5-ATP.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/6-Smarter.jpg
  fastlane/metadata/android/en-US/images/phoneScreenshots/7-Fire.jpg
Labels: QA-Optional

#4069 Bookmark translations
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/donottranslate.xml
  app/src/main/res/values/strings.xml
Labels: QA-Optional

#4081 Update content scope scripts to version 4.59.1
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4094 Translations for "never save for this site" feature
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Labels: QA-Optional

#4078 Android: Rename files to avoid confusion
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/MediaCaptureResultHandler.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/launcher/UploadFromExternalMediaAppLauncher.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/permission/RealExternalMediaSystemPermissionsHelper.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/postprocess/DeleteMediaCaptureWorker.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/postprocess/MediaCaptureDelayedDeleter.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/postprocess/MediaCaptureImageMover.kt
Labels: STACKED PR - DO NOT MERGE, QA-Optional

#4122 Update content scope scripts to version 4.59.2
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4092 New persistent notif behavior for VPN
  app-tracking-protection/vpn-api-test/src/main/java/com/duckduckgo/mobile/android/vpn/service/FakeVpnEnabledNotificationContentPlugin.kt
  app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnEnabledNotificationContentPlugin.kt
  app-tracking-protection/vpn-api/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnReminderNotificationContentPlugin.kt
  app-tracking-protection/vpn-impl/src/main/AndroidManifest.xml
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/VpnTrackerNotificationUpdates.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/notification/AppTPAndNetPEnabledNotificationContentPlugin.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/notification/AppTpDisabledContentPlugin.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/notification/AppTpEnabledNotificationContentPlugin.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/notification/AppTpRevokedContentPlugin.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/notification/PersistentNotificationDismissedReceiver.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/service/notification/VpnNotificationStore.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/alwayson/AlwaysOnLockDownDetector.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldAlertNotificationBuilder.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldNotificationFactory.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/VpnEnabledNotificationBuilder.kt
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/ui/notification/VpnReminderNotificationBuilder.kt
  app-tracking-protection/vpn-impl/src/main/res/layout/notification_device_shield_disabled.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/notification_device_shield_report.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/notification_device_shield_revoked.xml
  app-tracking-protection/vpn-impl/src/main/res/layout/notification_vpn_enabled.xml
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/service/notification/AppTPAndNetPEnabledNotificationContentPluginTest.kt
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/service/notification/AppTpEnabledNotificationContentPluginTest.kt
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/notification/AppTPReminderNotificationSchedulerTest.kt
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldDailyNotificationFactoryTest.kt
  app-tracking-protection/vpn-impl/src/test/java/com/duckduckgo/mobile/android/vpn/ui/notification/DeviceShieldWeeklyNotificationFactoryTest.kt
  network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/notification/NetPDisabledNotificationBuilder.kt
  network-protection/network-protection-impl/src/main/java/com/duckduckgo/networkprotection/impl/notification/NetPEnabledNotificationContentPlugin.kt
  network-protection/network-protection-impl/src/main/res/drawable/ic_netp_warning.xml
  network-protection/network-protection-impl/src/main/res/layout/notification_netp_disabled.xml
  network-protection/network-protection-impl/src/main/res/layout/notification_netp_disabled_by_vpn.xml
  network-protection/network-protection-impl/src/main/res/values/donottranslate.xml
  network-protection/network-protection-impl/src/test/java/com/duckduckgo/networkprotection/impl/notification/NetPEnabledNotificationContentPluginTest.kt
Labels: DO NOT MERGE

#4082 Autofill, support deleting all passwords, api changes
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStore.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/securestorage/SecureStorage.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/store/InternalAutofillStore.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStoreTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/securestorage/RealSecureStorageTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/FakeSecureStorage.kt
  autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/SecureStorageRepository.kt
  autofill/autofill-store/src/main/java/com/duckduckgo/securestorage/store/db/WebsiteLoginCredentialsDao.kt
Labels: STACKED PR - DO NOT MERGE, QA-Optional

#4087 Autofill, support deleting all passwords, UI changes
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deviceauth/AuthLauncher.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/deviceauth/DeviceAuthenticator.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillManagementActivity.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModel.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementCredentialsMode.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/credential/management/viewing/AutofillManagementListMode.kt
  autofill/autofill-impl/src/main/res/layout/fragment_autofill_management_list_mode.xml
  autofill/autofill-impl/src/main/res/menu/autofill_list_mode_menu.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deviceauth/FakeAuthenticator.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/deviceauth/RealDeviceAuthenticatorTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/credential/management/AutofillSettingsViewModelTest.kt
  autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
  autofill/autofill-internal/src/main/res/layout/activity_autofill_internal_settings.xml
  autofill/autofill-internal/src/main/res/values/donottranslate.xml
Labels: STACKED PR - DO NOT MERGE

#4099 Autofill, support deleting all passwords, notifiy sync listener
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStore.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/CredentialsSyncMetadata.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/sync/SyncCredentialsListener.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/SecureStoreBackedAutofillStoreTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/CredentialsSyncMetadataTest.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/sync/SyncCredentialsListenerTest.kt
  autofill/autofill-store/src/main/java/com/duckduckgo/autofill/store/CredentialsSyncMetadataDao.kt
Labels: STACKED PR - DO NOT MERGE

#4113 Sync: Move releaseTest to Prod
  .github/workflows/sync-end-to-end.yml
  .maestro/sync_flows/create_account.yaml
  .maestro/sync_flows/delete_server_data.yaml
  .maestro/sync_flows/recover_account.yaml
Labels: QA-Optional

#4137 Remove onByDefault autofill pixel parameter
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelInterceptor.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelInterceptorTest.kt
Labels: QA-Optional
