Repository duckduckgo/Android, pull requests merged in 2024-02, with the labels that each got.

#4052 Android: Add support for the capture field (#4048)
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
  app/src/main/java/com/duckduckgo/app/browser/di/BrowserModule.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/camera/CameraCaptureResultHandler.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/camera/launcher/UploadFromExternalCameraLauncher.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/MediaCaptureResultHandler.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/launcher/UploadFromExternalMediaAppLauncher.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/permission/RealExternalMediaSystemPermissionsHelper.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/postprocess/DeleteMediaCaptureWorker.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/postprocess/MediaCaptureDelayedDeleter.kt
  app/src/main/java/com/duckduckgo/app/browser/filechooser/capture/postprocess/MediaCaptureImageMover.kt
  app/src/main/java/com/duckduckgo/app/browser/mediaplayback/MediaPlayback.kt
  app/src/main/java/com/duckduckgo/app/browser/mediaplayback/MediaPlaybackFeature.kt
  app/src/main/java/com/duckduckgo/app/browser/mediaplayback/UnusedMediaPlaybackFeatureFeatureCodegenTrigger.kt
  app/src/main/java/com/duckduckgo/app/browser/mediaplayback/store/MediaPlaybackDao.kt
  app/src/main/java/com/duckduckgo/app/browser/mediaplayback/store/MediaPlaybackDatabase.kt
  app/src/main/java/com/duckduckgo/app/browser/mediaplayback/store/MediaPlaybackExceptionEntity.kt
  app/src/main/java/com/duckduckgo/app/browser/mediaplayback/store/MediaPlaybackRepository.kt
  app/src/main/java/com/duckduckgo/app/browser/mediaplayback/store/MediaPlaybackStore.kt
  app/src/main/res/values/donottranslate.xml
  app/src/test/java/com/duckduckgo/app/browser/mediaplayback/store/RealMediaPlaybackRepositoryTest.kt
Labels: STACKED PR - DO NOT MERGE

#4158 Remove NYTimes from page loaded pixel allowlist
  app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandler.kt
Labels: QA-Optional

#4174 Update content scope scripts to version 4.63.0
  node_modules/@duckduckgo/content-scope-scripts/README.md
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4165 Translate autofill delete-all passwords feature
  app/src/main/res/values-hu/strings.xml
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/donottranslate.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
Labels: QA-Optional

#4146 Migrate autoconsent to the new feature flags system
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/androidTest/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandlerTest.kt
  app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedHandler.kt
  app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedOfflinePixelSender.kt
  app/src/main/java/com/duckduckgo/app/browser/pageloadpixel/PageLoadedPixelEntity.kt
  app/src/main/java/com/duckduckgo/app/cta/ui/Cta.kt
  app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
  app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
  autoconsent/autoconsent-api/src/main/java/com/duckduckgo/autoconsent/api/Autoconsent.kt
  autoconsent/autoconsent-impl/build.gradle
  autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/AutoconsentFeaturePlugin.kt
  autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/AutoconsentFeatureTogglesPlugin.kt
  autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/RealAutoconsent.kt
  autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/di/AutoconsentModule.kt
  autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/handlers/InitMessageHandlerPlugin.kt
  autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/remoteconfig/AutoconsentExceptionsRepository.kt
  autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/remoteconfig/AutoconsentExceptionsStore.kt
  autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/remoteconfig/AutoconsentFeature.kt
  autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/remoteconfig/AutoconsentFeatureModels.kt
  autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/remoteconfig/AutoconsentFeatureSettingsRepository.kt
  autoconsent/autoconsent-impl/src/main/java/com/duckduckgo/autoconsent/impl/remoteconfig/AutoconsentSettingsStore.kt
  autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/AutoconsentFeaturePluginTest.kt
  autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/AutoconsentFeatureTogglesPluginTest.kt
  autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/RealAutoconsentTest.kt
  autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/handlers/InitMessageHandlerPluginTest.kt
  autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/remoteconfig/RealAutoconsentExceptionsRepositoryTest.kt
  autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/remoteconfig/RealAutoconsentFeatureSettingsRepositoryTest.kt
  autoconsent/autoconsent-impl/src/test/java/com/duckduckgo/autoconsent/impl/ui/AutoconsentSettingsViewModelTest.kt
  autoconsent/autoconsent-store/src/main/java/com/duckduckgo/autoconsent/store/AutoconsentDao.kt
  autoconsent/autoconsent-store/src/main/java/com/duckduckgo/autoconsent/store/AutoconsentFeatureToggleRepository.kt
  autoconsent/autoconsent-store/src/main/java/com/duckduckgo/autoconsent/store/AutoconsentFeatureToggleStore.kt
  autoconsent/autoconsent-store/src/main/java/com/duckduckgo/autoconsent/store/AutoconsentSettingsDataStore.kt
  autoconsent/autoconsent-store/src/main/java/com/duckduckgo/autoconsent/store/AutoconsentSettingsRepository.kt
Labels: DO NOT MERGE

#4186 Add GH workflow to run critical autofill tests each night
  .github/workflows/e2e-nightly-autofill.yml
  .maestro/autofill/0_all.yaml
  .maestro/autofill/1_autofill_shown_in_overflow.yaml
  .maestro/autofill/2_autofill_add_search_update_delete_creds.yaml
  .maestro/autofill/2_autofill_reach_creds_management.yaml
  .maestro/autofill/3_autofill_prompted_to_save_creds_on_form.yaml
  .maestro/autofill/steps/2_script.js
  .maestro/autofill/steps/access_passwords_screen.yaml
  .maestro/autofill/steps/delete_logins.yaml
  .maestro/autofill/steps/manual_update.yaml
  .maestro/autofill/steps/search_logins.yaml
Labels: QA-Optional

#4200 Remove SDK checks from AppLinksLauncher
  app/src/main/java/com/duckduckgo/app/browser/applinks/AppLinksLauncher.kt
Labels: QA-Optional

#4188 Update content scope scripts to version 4.64.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#4199 Removes detection for when Autofill dialogs would overlap
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  autofill/autofill-api/src/main/java/com/duckduckgo/autofill/api/dialog/AutofillOverlappingDialogDetector.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/pixel/AutofillPixelNames.kt
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/DefaultAutofillOverlappingDialogDetector.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/DefaultAutofillOverlappingDialogDetectorTest.kt
Labels: QA-Optional

#4211 Update reference tests to version 1708702034
  app/src/test/resources/reference_tests/brokensites/tests.json
  package-lock.json
  package.json
Labels: reference tests, automated pr

#4219 Update content scope scripts to version 5.0.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts
