Repository duckduckgo/Android, pull requests merged in 2025-02, with the labels that each got.

#5584 Export Feature Flag Inventory so it can be accessed more quickly
  feature-toggles/feature-toggles-internal/src/main/AndroidManifest.xml
Labels: QA-Optional

#5538 Address feedback and known issues for Tracker Blocking Animation
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/PulseAnimation.kt
  app/src/main/java/com/duckduckgo/app/browser/animations/ExperimentTrackersAnimationHelper.kt
  app/src/main/java/com/duckduckgo/app/browser/animations/LottieExperimentTrackersAnimationHelper.kt
  app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/TopAppBarBehavior.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/TrackersBlockedViewSlideBehavior.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/animations/BrowserLottieTrackersAnimatorHelper.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/animations/BrowserTrackersAnimatorHelper.kt
  app/src/main/java/com/duckduckgo/app/global/model/SiteMonitor.kt
  app/src/main/res/drawable/ic_circle_pulse_green.xml
  app/src/main/res/layout/fragment_browser_tab.xml
  app/src/main/res/raw/shieldburst.json
  app/src/main/res/raw/trackers_burst.json
  app/src/main/res/values-pl/strings.xml
  browser-api/src/main/java/com/duckduckgo/app/global/model/Site.kt
Labels: STACKED PR - DO NOT MERGE

#5536 Translations for Tracker Blocking Animation
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/PulseAnimation.kt
  app/src/main/java/com/duckduckgo/app/browser/animations/ExperimentTrackersAnimationHelper.kt
  app/src/main/java/com/duckduckgo/app/browser/animations/LottieExperimentTrackersAnimationHelper.kt
  app/src/main/java/com/duckduckgo/app/browser/animations/RealPrivacyDashboardExternalPixelParams.kt
  app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/TopAppBarBehavior.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/TrackersBlockedViewSlideBehavior.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/animations/BrowserLottieTrackersAnimatorHelper.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/animations/BrowserTrackersAnimatorHelper.kt
  app/src/main/java/com/duckduckgo/app/global/model/SiteMonitor.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/main/res/drawable/ic_circle_pulse_green.xml
  app/src/main/res/layout/fragment_browser_tab.xml
  app/src/main/res/layout/view_new_omnibar.xml
  app/src/main/res/layout/view_new_omnibar_bottom.xml
  app/src/main/res/raw/shieldburst.json
  app/src/main/res/raw/trackers_burst.json
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModelTest.kt
  browser-api/src/main/java/com/duckduckgo/app/global/model/Site.kt
  privacy-dashboard/privacy-dashboard-api/src/main/java/com/duckduckgo/privacy/dashboard/api/PrivacyDashboardExternalPixelsPlugin.kt
  privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModel.kt
  privacy-dashboard/privacy-dashboard-impl/src/test/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModelTest.kt
  statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
  subscriptions/subscriptions-impl/src/main/res/values-pl/strings-subscriptions.xml
Labels: STACKED PR - DO NOT MERGE

#5526 Update the code to use the feature flags
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/androidTest/java/com/duckduckgo/app/browser/omnibar/animations/LottiePrivacyShieldAnimationHelperTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/PulseAnimation.kt
  app/src/main/java/com/duckduckgo/app/browser/animations/ExperimentTrackersAnimationHelper.kt
  app/src/main/java/com/duckduckgo/app/browser/animations/LottieExperimentTrackersAnimationHelper.kt
  app/src/main/java/com/duckduckgo/app/browser/animations/RealPrivacyDashboardExternalPixelParams.kt
  app/src/main/java/com/duckduckgo/app/browser/commands/Command.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/TopAppBarBehavior.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/TrackersBlockedViewSlideBehavior.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/animations/BrowserLottieTrackersAnimatorHelper.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/animations/BrowserTrackersAnimatorHelper.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/animations/LottiePrivacyShieldAnimationHelper.kt
  app/src/main/java/com/duckduckgo/app/global/model/SiteMonitor.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/main/res/drawable/ic_circle_pulse_green.xml
  app/src/main/res/layout/fragment_browser_tab.xml
  app/src/main/res/layout/view_new_omnibar.xml
  app/src/main/res/layout/view_new_omnibar_bottom.xml
  app/src/main/res/raw/shieldburst.json
  app/src/main/res/raw/trackers_burst.json
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/duckduckgo/app/browser/omnibar/OmnibarLayoutViewModelTest.kt
  browser-api/src/main/java/com/duckduckgo/app/global/model/Site.kt
  privacy-dashboard/privacy-dashboard-api/src/main/java/com/duckduckgo/privacy/dashboard/api/PrivacyDashboardExternalPixelsPlugin.kt
  privacy-dashboard/privacy-dashboard-impl/src/main/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModel.kt
  privacy-dashboard/privacy-dashboard-impl/src/test/java/com/duckduckgo/privacy/dashboard/impl/ui/PrivacyDashboardHybridViewModelTest.kt
  statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
  subscriptions/subscriptions-impl/src/main/res/values-pl/strings-subscriptions.xml
Labels: STACKED PR - DO NOT MERGE

#5590 Update content scope scripts to version 7.13.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5596 Update content scope scripts to version 7.16.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5620 Update content scope scripts to version 7.17.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5642 Update content scope scripts to version 7.18.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5647 enable compatibility mode in autofill service
  autofill/autofill-impl/src/main/res/xml/service_configuration.xml
Labels: QA-Optional

#5661 Update reference tests to version 1739774089
  package-lock.json
  package.json
Labels: reference tests, automated pr

#5674 Update content scope scripts to version 7.20.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.css
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/bg/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/cs/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/da/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/de/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/el/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/en/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/es/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/et/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/fi/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/fr/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/hr/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/hu/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/it/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/lt/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/lv/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/nb/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/nl/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/pl/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/pt/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/ro/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/ru/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/sk/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/sl/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/sv/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/tr/duckplayer.json
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5687 Update content scope scripts to version 7.22.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5644 Tab Switcher Animation: Introduce TabSwitcherAnimation feature toggle
  app/src/main/java/com/duckduckgo/app/tabs/TabSwitcherAnimationFeature.kt
Labels: QA-Optional

#5712 Update content scope scripts to version 7.23.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.css
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts
