Repository duckduckgo/Android, pull requests merged in 2025-05, with the labels that each got.

#5993 Update content scope scripts to version 8.18.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#6001 Fix wrong icon attribute
  common/common-ui/src/main/res/drawable/ic_shield_16.xml
  common/common-ui/src/main/res/drawable/ic_shield_disabled_16.xml
Labels: QA-Optional

#6016 Update reference tests to version 1746537866
  package-lock.json
  package.json
Labels: reference tests, automated pr

#6015 Visual design: small icon version in omnibar
  app/src/main/res/layout/view_fade_omnibar.xml
  common/common-ui/src/main/res/drawable/ic_arrow_left_small_24.xml
Labels: QA-Optional

#6007 Fix: NTP creation crash with tab swiping
  app/src/main/java/com/duckduckgo/app/browser/tabs/DefaultTabManager.kt
  app/src/test/java/com/duckduckgo/app/browser/tabs/DefaultTabManagerTest.kt
Labels: QA-Optional

#6023 Visual design: May colors
  app/src/main/res/layout/view_fade_omnibar.xml
  common/common-ui/src/main/res/drawable/ic_close_24_secondary.xml
  common/common-ui/src/main/res/drawable/ic_close_circle_small_secondary_24.xml
  common/common-ui/src/main/res/values/design-experiments-colors.xml
Labels: QA-Optional

#6059 Visual design: fix protections disabled button
  common/common-ui/src/main/res/drawable/ic_shield_disabled_16.xml
Labels: QA-Optional

#6053 Update content scope scripts to version 8.21.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#6025 Tab swiping: Clean up unused fixes behind feature flags
  app/src/main/java/com/duckduckgo/app/browser/tabs/adapter/FragmentStateAdapter.java
  app/src/main/java/com/duckduckgo/app/browser/tabs/adapter/FragmentViewHolder.kt
  common/common-ui/src/main/java/com/duckduckgo/common/ui/tabs/SwipingTabsFeature.kt
  common/common-ui/src/main/java/com/duckduckgo/common/ui/tabs/SwipingTabsFeatureProvider.kt
Labels: QA-Optional

#6070 Update content scope scripts to version 8.22.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#6094 Add WebView dev settings screen for internal builds
  app/src/internal/AndroidManifest.xml
  app/src/internal/java/com/duckduckgo/app/browser/webview/WebViewDevSettings.kt
  app/src/internal/java/com/duckduckgo/app/browser/webview/WebViewDevSettingsActivity.kt
  app/src/internal/java/com/duckduckgo/app/browser/webview/WebViewDevSettingsViewModel.kt
  app/src/internal/java/com/duckduckgo/app/browser/webview/WebViewInformationExtractor.kt
  app/src/internal/res/layout/activity_web_view_dev_settings.xml
  app/src/internal/res/values/donottranslate.xml
  internal-features/internal-features-api/src/main/java/com/duckduckgo/internal/features/api/InternalFeaturePlugin.kt
Labels: QA-Optional

#6096 Update content scope scripts to version 8.24.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#6113 Fix ANR produced in RemoteDomainTargetAppDataDownloader
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/mapper/RemoteDomainTargetAppDataDownloader.kt
Labels: QA-Optional

#6085 ContributesRemoteFeatureCodeGeneratorBucketAssignmentTest can be flakey; add logs for when it next fails
  feature-toggles/feature-toggles-impl/src/test/java/com/duckduckgo/feature/toggles/codegen/ContributesRemoteFeatureCodeGeneratorBucketAssignmentTest.kt
Labels: QA-Optional

#6132 Duck chat: Search Assist link feature
  common/common-ui/src/main/res/drawable/ic_assist_24.xml
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/pixel/DuckChatDailyPixelSender.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/pixel/DuckChatPixels.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatSettingsActivity.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatSettingsViewModel.kt
  duckchat/duckchat-impl/src/main/res/layout/activity_duck_chat_settings.xml
  duckchat/duckchat-impl/src/main/res/values-bg/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-cs/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-da/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-de/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-el/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-es/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-et/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-fi/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-fr/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-hr/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-hu/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-it/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-lt/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-lv/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-nb/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-nl/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-pl/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-pt/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-ro/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-ru/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-sk/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-sl/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-sv/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values-tr/strings-duckchat.xml
  duckchat/duckchat-impl/src/main/res/values/strings-duckchat.xml
  duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/DuckChatSettingsViewModelTest.kt
  statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Labels: QA-Optional

#6122 Submit strings for translation
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/donottranslate.xml
  app/src/main/res/values/strings.xml
  network-protection/network-protection-impl/src/main/res/values-bg/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-cs/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-da/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-de/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-el/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-es/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-et/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-fi/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-fr/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-hr/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-hu/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-it/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-lt/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-lv/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-nb/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-nl/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-pl/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-pt/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-ro/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-ru/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-sk/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-sl/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-sv/strings-netp.xml
  network-protection/network-protection-impl/src/main/res/values-tr/strings-netp.xml
Labels: Pending Translations

#6146 Update non-critical Autofill tests so they can run against internal builds again
  .maestro/autofill/1_autofill_shown_in_overflow.yaml
  .maestro/autofill/2_autofill_add_search_update_delete_creds.yaml
  .maestro/autofill/3_autofill_prompted_to_save_creds_on_form.yaml
  .maestro/autofill/4_autofill_settings_creds.yaml
  .maestro/autofill/backfillingUsername/multi_step_login_username_backfilled.yaml
  .maestro/autofill/backfillingUsername/multi_step_login_username_backfilled_for_an_update.yaml
  .maestro/autofill/backfillingUsername/multi_step_login_username_not_backfilled_if_provided_explicitly.yaml
  .maestro/autofill/backfillingUsername/multi_step_registration_username_backfilled_password_autogenerated.yaml
  .maestro/autofill/backfillingUsername/multi_step_registration_username_backfilled_password_manually_entered.yaml
  .maestro/autofill/backfillingUsername/password_reset_flow_autogenerated_password.yaml
  .maestro/autofill/backfillingUsername/password_reset_flow_for_existing_credential_generated_password.yaml
  .maestro/autofill/backfillingUsername/password_reset_flow_for_existing_credential_manual_password.yaml
  .maestro/autofill/passwordGeneration/autosaves_credential_when_password_generated_with_username.yaml
  .maestro/autofill/passwordGeneration/autosaves_credential_when_password_generated_without_username.yaml
  autofill/autofill-impl/build.gradle
Labels: QA-Optional

#6151 Update content scope scripts to version 9.0.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts
