Repository duckduckgo/Android, pull requests merged in 2025-06, with the labels that each got.

#6202 GHA: Lint workflows
  .github/workflows/test_workflow.yml
  .github/workflows/validate_workflows.yml
Labels: QA-Optional

#6205 Update content scope scripts to version 9.5.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/bg/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/cs/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/da/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/de/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/el/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/es/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/et/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/fi/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/fr/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/hr/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/hu/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/it/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/lt/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/lv/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/nb/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/nl/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/pl/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/pt/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/ro/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/ru/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/sk/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/sl/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/sv/duckplayer.json
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/locales/tr/duckplayer.json
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#6208 Fix Duck.ai shortcut not showing on internal
  app/src/main/java/com/duckduckgo/app/global/shortcut/AppShortcutCreator.kt
Labels: QA-Optional

#6252 Update content scope scripts to version 9.9.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#6257 Show favorites in search interstitial
  duckchat/duckchat-impl/build.gradle
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatOmnibarLayout.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/SearchInterstitialActivity.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/SearchInterstitialFragment.kt
  duckchat/duckchat-impl/src/main/res/layout/activity_search_interstitial.xml
  duckchat/duckchat-impl/src/main/res/layout/fragment_search_interstitial.xml
Labels: PR-task

#6241 Integration with Duck.ai session
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/navigation/AppBrowserNav.kt
  app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
  app/src/main/res/layout/activity_browser.xml
  app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
  browser-api/src/main/java/com/duckduckgo/app/tabs/BrowserNav.kt
  common/common-utils/src/main/java/com/duckduckgo/common/utils/extensions/ActivityExtensions.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/feature/DuckChatFeature.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/pixel/DuckChatPixels.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/repository/DuckChatFeatureRepository.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/store/DuckChatDataStore.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewFragment.kt
  duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/RealDuckChatTest.kt
Labels: PR-task

#6279 Fix clipped mic icon
  voice-search/voice-search-impl/src/main/res/layout/view_voice_recognizing_indicator.xml
Labels: QA-Optional

#6288 GHA: Remove label need for Sync workflow
  .github/workflows/action-pr-sync.yaml
Labels: QA-Optional

#6284 PIR: Implement json action retry on failure
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/PirActionsRunner.kt
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/BrokerStepCompletedEventHandler.kt
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/CaptchaInforReceivedEventHandler.kt
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/CaptchaServiceFailedEventHandler.kt
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/EmailFailedEventHandler.kt
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/EmailReceivedEventHandler.kt
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/ExecuteBrokerStepActionEventHandler.kt
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/ExecuteNextBrokerStepEventHandler.kt
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/JsActionFailedEventHandler.kt
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/JsActionSuccessEventHandler.kt
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/JsErrorReceivedEventHandler.kt
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/LoadUrlCompleteEventHandler.kt
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/PirActionsRunnerStateEngine.kt
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/actions/RealPirActionsRunnerStateEngine.kt
Labels: PR-task

#6267 add missing discovery param to autofill_settings_opened pixel
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/ui/settings/AutofillSettingsViewModel.kt
  autofill/autofill-impl/src/test/java/com/duckduckgo/autofill/impl/ui/settings/AutofillSettingsViewModelTest.kt
Labels: PR-task

#6314 Update content scope scripts to version 10.2.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts
