Repository duckduckgo/Android, pull requests merged in 2025-04, with the labels that each got.

#5847 [Android] Increase in 5xx errors
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/httperrors/HttpErrorDailyReportingWorker.kt
  app/src/main/java/com/duckduckgo/app/browser/httperrors/HttpErrorPixels.kt
  app/src/main/java/com/duckduckgo/app/pixels/remoteconfig/AndroidBrowserConfigFeature.kt
  app/src/test/java/com/duckduckgo/app/browser/httperrors/HttpErrorDailyReportingWorkerTest.kt
  app/src/test/java/com/duckduckgo/app/browser/httperrors/RealHttpErrorPixelsTest.kt
Labels: QA-Optional

#5855 Reorganize duckchat module
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/settings/SettingsPixelDispatcher.kt
  app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
  app/src/test/java/com/duckduckgo/app/settings/SettingsPixelDispatcherTest.kt
  app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
  duckchat/duckchat-impl/src/main/AndroidManifest.xml
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/RealDuckChat.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/di/DuckChatDataStoreModule.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/feature/AIChatDownloadFeature.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/feature/DuckChatFeature.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/helper/DuckChatJSHelper.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/pixel/DuckChatPixels.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/repository/DuckChatFeatureRepository.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/store/DuckChatDataStore.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatSettingsActivity.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatSettingsViewModel.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewActivity.kt
  duckchat/duckchat-impl/src/main/java/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewClient.kt
  duckchat/duckchat-impl/src/main/res/layout/activity_duck_chat_settings.xml
  duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/RealDuckChatTest.kt
  duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/helper/RealDuckChatJSHelperTest.kt
  duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/repository/DuckChatFeatureRepositoryTest.kt
  duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/store/SharedPreferencesDuckChatDataStoreTest.kt
  duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/DuckChatSettingsViewModelTest.kt
  duckchat/duckchat-impl/src/test/kotlin/com/duckduckgo/duckchat/impl/ui/DuckChatWebViewClientTest.kt
Labels: QA-Optional

#5856 Update content scope scripts to version 8.11.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5860 GHA: Update to latest version
  .github/workflows/action-issue-opened.yaml
  .github/workflows/action-pr-merged.yaml
  .github/workflows/action-pr-opened.yaml
  .github/workflows/custom-tabs-nightly.yml
  .github/workflows/e2e-nightly-autofill.yml
  .github/workflows/pr-review-notifications.yaml
  .github/workflows/ps-review-analysis.yml
  .github/workflows/release_create_tag.yml
  .github/workflows/release_create_task.yml
  .github/workflows/release_nightly.yml
  .github/workflows/release_tests.yml
  .github/workflows/release_update_release_notes.yml
  .github/workflows/release_upload_play_store.yml
  .github/workflows/sync-critical-path.yml
  .github/workflows/update-content-scope.yml
  .github/workflows/update-ref-tests.yml
Labels: QA-Optional

#5859 Fix multi-tab Maestro test
  .maestro/privacy_tests/6_-_Multi-tab.yaml
Labels: QA-Optional

#5868 Update content scope scripts to version 8.12.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5867 Update reference tests to version 1743747763
  package-lock.json
  package.json
Labels: reference tests, automated pr

#5874 Sync: guard against malformed json when polling
  sync/sync-impl/src/main/java/com/duckduckgo/sync/impl/SyncAccountRepository.kt
  sync/sync-impl/src/test/java/com/duckduckgo/sync/impl/AppSyncAccountRepositoryTest.kt
Labels: QA-Optional

#5881 Update content scope scripts to version 8.13.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5885 Fix: FragmentStateAdapter IllegalStateException
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
  app/src/main/java/com/duckduckgo/app/browser/SwipingTabsFeature.kt
  app/src/main/java/com/duckduckgo/app/browser/SwipingTabsFeatureProvider.kt
  app/src/main/java/com/duckduckgo/app/browser/tabs/adapter/FragmentStateAdapter.java
  app/src/main/java/com/duckduckgo/app/browser/tabs/adapter/FragmentViewHolder.kt
  app/src/main/java/com/duckduckgo/app/browser/tabs/adapter/TabPagerAdapter.kt
  app/src/test/java/com/duckduckgo/app/browser/BrowserViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
  versions.properties
Labels: QA-Optional

#5895 Update content scope scripts to version 8.14.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5894 Remove m_dedicated_webview* pixels
  app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
  app/src/main/java/com/duckduckgo/app/browser/webview/WebViewActivity.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
Labels: QA-Optional

#5899 PIR/Internal: Remove recordId from pixels
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/common/PirRunStateHandler.kt
  pir/pir-internal/src/main/java/com/duckduckgo/pir/internal/pixels/PirPixelSender.kt
Labels: QA-Optional

#5900 Remove OS_VERSION from PixelParamRemovalPlugin
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/pixels/VpnPixelParamRemovalPlugin.kt
  app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
  app/src/test/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptorTest.kt
  common/common-utils/src/main/java/com/duckduckgo/common/utils/plugins/pixel/PixelParamRemovalPlugin.kt
  downloads/downloads-impl/src/main/java/com/duckduckgo/downloads/impl/pixels/DownloadsPixelName.kt
  statistics/statistics-api/src/main/java/com/duckduckgo/app/statistics/pixels/Pixel.kt
Labels: QA-Optional

#5898 Remove obsolete maestro test and add one for the dismissal of Dax fire dialog
  .maestro/fire_button/dimiss_fire_during_onboarding.yaml
  .maestro/fire_button/fire_dialog_during_onboarding.yaml
Labels: QA-Optional

#5906 Renamed tests to avoid Robin errors due to name conflict.
  .maestro/onboarding/onboarding_dismiss_all_dialogs.yaml
  .maestro/onboarding/onboarding_dismiss_try_a_search_dialog.yaml
Labels: QA-Optional

#5910 GHA: Update Asana Sync to 1.8
  .github/workflows/action-issue-opened.yaml
  .github/workflows/action-pr-merged.yaml
  .github/workflows/action-pr-opened.yaml
  .github/workflows/custom-tabs-nightly.yml
  .github/workflows/e2e-nightly-autofill.yml
  .github/workflows/pr-review-notifications.yaml
  .github/workflows/ps-review-analysis.yml
  .github/workflows/release_create_tag.yml
  .github/workflows/release_create_task.yml
  .github/workflows/release_nightly.yml
  .github/workflows/release_tests.yml
  .github/workflows/release_update_release_notes.yml
  .github/workflows/release_upload_play_store.yml
  .github/workflows/sync-critical-path.yml
  .github/workflows/update-content-scope.yml
  .github/workflows/update-ref-tests.yml
Labels: QA-Optional

#5942 Replace first() with firstOrNull() in BrokenSitePromptDataStore
  broken-site/broken-site-impl/src/main/java/com/duckduckgo/brokensite/impl/BrokenSitePomptDataStore.kt
Labels: QA-Optional

#5914 Translations.
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/donottranslate.xml
  app/src/main/res/values/strings.xml
Labels: STACKED PR - DO NOT MERGE

#5913 Added skip onboarding option for detected re-installers.
  .maestro/preonboarding/preonboarding_returning_user_show_tutorial.yaml
  .maestro/preonboarding/preonboarding_returning_user_start_browsing.yaml
  app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
  app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingActivity.kt
  app/src/main/java/com/duckduckgo/app/onboarding/ui/OnboardingViewModel.kt
  app/src/main/java/com/duckduckgo/app/onboarding/ui/page/OnboardingPageFragment.kt
  app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePage.kt
  app/src/main/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModel.kt
  app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
  app/src/main/res/layout/pre_onboarding_dax_dialog_cta.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/duckduckgo/app/onboarding/ui/OnboardingViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/onboarding/ui/page/WelcomePageViewModelTest.kt
Labels: STACKED PR - DO NOT MERGE

#5945 Visual deisgn: Omnibar touch feedback
  common/common-ui/src/main/res/drawable/bottom_nav_fire_button_foreground.xml
  common/common-ui/src/main/res/drawable/selectable_item_experimental_background.xml
Labels: QA-Optional

#5946 Visual design: Secondary color for clear icon in Omnibar
  app/src/main/res/layout/view_fade_omnibar.xml
  common/common-ui/src/main/res/drawable/ic_close_24_secondary.xml
Labels: QA-Optional

#5959 Update reference tests to version 1745528586
  package-lock.json
  package.json
Labels: reference tests, automated pr

#5974 Fix omnibar-related Maestro tests
  .maestro/autofill/backfillingUsername/multi_step_login_username_backfilled.yaml
  .maestro/autofill/backfillingUsername/multi_step_login_username_backfilled_for_an_update.yaml
  .maestro/autofill/backfillingUsername/multi_step_login_username_not_backfilled_if_provided_explicitly.yaml
  .maestro/autofill/backfillingUsername/multi_step_registration_username_backfilled_password_autogenerated.yaml
  .maestro/autofill/backfillingUsername/multi_step_registration_username_backfilled_password_manually_entered.yaml
  .maestro/autofill/backfillingUsername/password_reset_flow_autogenerated_password.yaml
  .maestro/autofill/backfillingUsername/password_reset_flow_for_existing_credential_generated_password.yaml
  .maestro/autofill/passwordGeneration/autosaves_credential_when_password_generated_with_username.yaml
  .maestro/autofill/passwordGeneration/autosaves_credential_when_password_generated_without_username.yaml
  .maestro/bookmarks/ensure_bookmarks_can_be_added_and_deleted.yaml
  .maestro/bookmarks/open_bookmark_and_navigate_back.yaml
  .maestro/bookmarks/open_bookmark_in_folder_and_navigate_back.yaml
  .maestro/browsing/visit_site.yaml
  .maestro/favorites/favorites_bookmarks_add.yaml
  .maestro/favorites/favorites_bookmarks_delete.yaml
  .maestro/fire_button/dimiss_fire_during_onboarding.yaml
  .maestro/fire_button/fire_during_onboarding.yaml
  .maestro/ppro/launch_privacy_pro_from_special_url.yaml
  .maestro/preonboarding/preonboarding_returning_user_start_browsing.yaml
  .maestro/sync_flows/steps/action_add_bookmarks_and_folders.yaml
  .maestro/tabs/open_multiple_tabs.yaml
Labels: QA-Optional
