Repository duckduckgo/Android, pull requests merged in 2025-01, with the labels that each got.

#5438 Update content scope scripts to version 6.44.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5435 Update Styleguide file
  CONTRIBUTING.md
  STYLEGUIDE.md
Labels: QA-Optional

#5436 Execute UI tests on Robin instead of Maestro-Cloud
  .github/workflows/ads-end-to-end.yml
  .github/workflows/custom-tabs-nightly.yml
  .github/workflows/e2e-nightly-autofill.yml
  .github/workflows/end-to-end.yml
  .github/workflows/privacy-dashboard-end-to-end.yml
  .github/workflows/release_tests.yml
  .github/workflows/sync-critical-path.yml
  .maestro/ads_preview_flows/1-_design-system-components.yaml
Labels: QA-Optional

#5439 ADS: Remove all legacy colors
  app-tracking-protection/vpn-impl/src/main/java/com/duckduckgo/mobile/android/vpn/breakage/ReportBreakageAppListActivity.kt
  app-tracking-protection/vpn-impl/src/main/res/drawable/ic_baseline_feedback_24.xml
  app-tracking-protection/vpn-impl/src/main/res/drawable/ic_block.xml
  app/lint-baseline.xml
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/notification/model/ClearDataNotification.kt
  app/src/main/java/com/duckduckgo/app/notification/model/PrivacyProtectionNotification.kt
  app/src/main/java/com/duckduckgo/app/survey/ui/SurveyActivity.kt
  app/src/main/res/drawable/background_grey_border.xml
  app/src/main/res/drawable/background_grey_border_selected.xml
  app/src/main/res/drawable/ic_circle_pulse_blue.xml
  app/src/main/res/drawable/notification_info_top_background.xml
  app/src/main/res/drawable/report_broken_site_button_outlined_bg.xml
  app/src/main/res/drawable/search_favorites_widget_search_bar_background_light.xml
  app/src/main/res/layout-land/activity_add_widget_instructions.xml
  app/src/main/res/layout/activity_add_widget_instructions.xml
  app/src/main/res/layout/activity_user_survey.xml
  common/common-ui/src/main/res/values/design-system-colors.xml
  common/common-ui/src/main/res/values/design-system-theming.xml
  network-protection/network-protection-impl/src/main/res/drawable/ic_baseline_feedback_24.xml
  privacy-protections-popup/privacy-protections-popup-impl/src/main/res/drawable/ic_highlight_blue.xml
  subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/feedback/SubscriptionFeedbackSubmitFragment.kt
Labels: QA-Optional

#5446 Swiping tabs: Tests
  app/src/test/java/com/duckduckgo/app/browser/tabs/DefaultTabManagerTest.kt
Labels: QA-Optional

#5449 Update content scope scripts to version 7.2.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.css
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5454 Update content scope scripts to version 7.4.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5456 GHA: Ad-hoc build
  .github/workflows/build-ad-hoc.yml
Labels: QA-Optional

#5440 Only navigate to Duck Player if YT was loaded in mainframe
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserWebViewClientTest.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserWebViewClient.kt
  duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
  duckplayer/duckplayer-impl/src/test/kotlin/com/duckduckgo/duckplayer/impl/RealDuckPlayerTest.kt
Labels: QA-Optional

#5457 Reduce the high-count buckets
  app/src/main/java/com/duckduckgo/app/tabs/store/TabStatsBucketing.kt
  app/src/test/java/com/duckduckgo/app/tabs/store/TabStatsBucketingTest.kt
Labels: QA-Optional

#5458 Ensure LevelDB Iterator is closed
  app/src/main/java/com/duckduckgo/app/browser/weblocalstorage/WebLocalStorageManager.kt
  app/src/test/java/com/duckduckgo/app/browser/DuckDuckGoWebLocalStorageManagerTest.kt
Labels: QA-Optional

#5465 GHA: Allow for Play Release to tag any ref
  .github/workflows/build-ad-hoc.yml
  .github/workflows/release_upload_play_store.yml
Labels: QA-Optional

#5470 GHA: Allow ad-hoc workflow to build different variants
  .github/workflows/build-ad-hoc.yml
Labels: QA-Optional

#5473 Update content scope scripts to version 7.6.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5482 GHA: Update upload artifact version
  .github/workflows/docs.yml
Labels: QA-Optional

#5491 Update content scope scripts to version 7.7.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5506 Add feature flag to enable / disable the Tracker Blocking Animation
  app/src/main/java/com/duckduckgo/app/browser/apppersonality/AppPersonalityFeature.kt
Labels: QA-Optional

#5516 Trackers blocked animations and cookies animations playing inconsistently
  app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarLayout.kt
Labels: QA-Optional

#5529 Update content scope scripts to version 7.9.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.css
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/mobile-bg-GCRU67TC.jpg
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/player-bg-F7QLKTXS.jpg
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5527 Add WebView compatibility check before launching GPM in dev settings
  autofill/autofill-internal/src/main/java/com/duckduckgo/autofill/internal/AutofillInternalSettingsActivity.kt
Labels: QA-Optional

#5540 Update content scope scripts to version 7.10.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5539 Update reference tests to version 1737732449
  package-lock.json
  package.json
Labels: reference tests, automated pr

#5549 Show on App Launch: Use string resources for settings
  app/src/main/res/layout/activity_show_on_app_launch_setting.xml
Labels: QA-Optional

#5555 Update content scope scripts to version 7.12.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5560 Update reference tests to version 1738159777
  app/src/androidTest/resources/reference_tests/domain_matching_tests.json
  package-lock.json
  package.json
Labels: reference tests, automated pr
