Repository duckduckgo/Android, pull requests merged in 2025-08, with the labels that each got.

#6502 Update content scope scripts to version 11.2.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#6240 Omnibar position: Remove the feature flag
  app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
  app/src/main/java/com/duckduckgo/app/appearance/AppearanceActivity.kt
  app/src/main/java/com/duckduckgo/app/appearance/AppearanceViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabViewModel.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/ChangeOmnibarPositionFeature.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/OmnibarFeatureFlagObserver.kt
  app/src/main/java/com/duckduckgo/app/browser/omnibar/rmf/OmnibarPositionAttributeMatcher.kt
  app/src/test/java/com/duckduckgo/app/appearance/AppearanceViewModelTest.kt
  app/src/test/java/com/duckduckgo/app/browser/omnibar/rmf/OmnibarPositionAttributeMatcherPluginTest.kt
Labels: QA-Optional, PR-task

#6507 Update Input Screen setting copy
  duckchat/duckchat-impl/src/main/res/values/donottranslate.xml
Labels: QA-Optional

#6515 Remove the atb parameter from set as default pixels.
  app/src/main/java/com/duckduckgo/app/global/api/PixelParamRemovalInterceptor.kt
Labels: QA-Optional

#6518 Onboarding Experiment translations
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/donottranslate.xml
  app/src/main/res/values/strings.xml
Labels: QA-Optional

#6517 Translations: [Android] Roll out additional default browser prompts
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/donottranslate.xml
  app/src/main/res/values/strings.xml
Labels: QA-Optional

#6552 Rebranding & duck.ai paid translations (round 3)
  subscriptions/subscriptions-impl/src/main/res/values-bg/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-cs/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-da/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-de/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-el/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-es/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-et/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-fi/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-fr/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-hr/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-hu/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-it/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-lt/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-lv/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-nb/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-nl/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-pl/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-pt/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-ro/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-ru/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-sk/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-sl/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-sv/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values-tr/strings-subscriptions.xml
  subscriptions/subscriptions-impl/src/main/res/values/donottranslate.xml
  subscriptions/subscriptions-impl/src/main/res/values/strings-subscriptions.xml
Labels: QA-Optional

#6555 Ensure gradle wrapper is used in internal builds
  .github/workflows/release_nightly.yml
Labels: QA-Optional

#6558 Avoid usage of requireActivity in download callback
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
Labels: QA-Optional

#6566 Update copy for importing passwords from google for consistency
  autofill/autofill-impl/src/main/res/values-bg/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-cs/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-da/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-de/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-el/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-es/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-et/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fi/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-fr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-hu/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-it/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-lv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nb/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-nl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-pt/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ro/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-ru/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sk/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sl/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-sv/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values-tr/strings-autofill-impl.xml
  autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
  subscriptions/subscriptions-impl/src/main/res/values-pl/strings-subscriptions.xml
Labels: QA-Optional

#6594 Update spotless version, from 6.1.2 to 7.2.1
  code-formatting.gradle
  versions.properties
Labels: QA-Optional

#6598 Fix: Use the previous pixel to measure Duck.ai discovery in tab switcher
  app/src/main/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModel.kt
  app/src/test/java/com/duckduckgo/app/tabs/ui/TabSwitcherViewModelTest.kt
Labels: QA-Optional

#6619 Enable Gradle configuration cache
  .github/workflows/ci.yml
  .github/workflows/external-ref-tests.yml
  .github/workflows/nightly.yml
  gradle.properties
Labels: QA-Optional

#6640 Fix nightly builds to ensure they get the version number correctly
  .github/workflows/release_nightly.yml
Labels: QA-Optional

#6701 Update content scope scripts to version 11.12.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/adsjsContentScope.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts
