Repository duckduckgo/Android, pull requests merged in 2025-09, with the labels that each got.

#6745 Fix copy for [Android] Add Duck.ai entry points to widgets plus additional widgets
  app/src/main/res/values/donottranslate.xml
  app/src/main/res/values/strings.xml
Labels: QA-Optional

#6747 Fix design for [Android] Add Duck.ai entry points to widgets plus additional widgets
  app/src/main/res/drawable/search_widget_favorites_dark_background.xml
  app/src/main/res/drawable/search_widget_favorites_daynight_background.xml
  app/src/main/res/drawable/search_widget_favorites_light_background.xml
  app/src/main/res/values/dimens.xml
  common/common-ui/src/main/res/values/design-system-dimensions.xml
  common/common-ui/src/main/res/values/widgets.xml
Labels: QA-Optional

#6755 Update content scope scripts to version 11.16.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/adsjsContentScope.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#6773 Update content scope scripts to version 11.19.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#6796 Update content scope scripts to version 11.25.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#6813 Update reference tests to version 1758095627
  package-lock.json
  package.json
Labels: reference tests, automated pr

#6842 Add feature toggle for address bar trackers animation
  app/src/main/java/com/duckduckgo/app/browser/animations/AddressBarTrackersAnimationFeatureToggle.kt
  app/src/main/java/com/duckduckgo/app/browser/senseofprotection/SenseOfProtectionExperimentImpl.kt
  app/src/test/java/com/duckduckgo/app/browser/senseofprotection/SenseOfProtectionExperimentImplTest.kt
Labels: QA-Optional

#6856 Update content scope scripts to version 11.29.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/adsjsContentScope.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#6857 Update content scope scripts to version 11.30.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/adsjsContentScope.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts
