Repository duckduckgo/Android, pull requests merged in 2025-03, with the labels that each got.

#5719 Update AGP to 8.7
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  versions.properties
Labels: QA-Optional

#5704 ignore views not classified from autofilling
  autofill/autofill-impl/src/main/java/com/duckduckgo/autofill/impl/service/AutofillProviderSuggestions.kt
Labels: QA-Optional

#5726 Update content scope scripts to version 7.24.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5732 Update content scope scripts to version 7.25.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5743 Update content scope scripts to version 7.27.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5737 Update reference tests to version 1741215780
  package-lock.json
  package.json
Labels: reference tests, automated pr

#5750 Update content scope scripts to version 7.28.0
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5767 Move Duck.AI Settings Item below DuckPlayer
  app/src/main/res/layout/content_settings_main_settings.xml
Labels: QA-Optional

#5760 Update content scope scripts to version 7.29.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5790 FF onPageLoadStarted
  app/src/main/java/com/duckduckgo/app/browser/webview/MaliciousSiteBlockerWebViewIntegration.kt
Labels: QA-Optional

#5792 Update content scope scripts to version 8.0.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5800 Update content scope scripts to version 8.3.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/pages/duckplayer/dist/index.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5819 Update content scope scripts to version 8.5.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5830 Update content scope scripts to version 8.9.0
  node_modules/@duckduckgo/content-scope-scripts/build/android/autofillPasswordImport.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/brokerProtection.js
  node_modules/@duckduckgo/content-scope-scripts/build/android/contentScope.js
  package-lock.json
  package.json
Labels: automated pr, content scope scripts

#5826 Update reference tests to version 1743047884
  malicious-site-protection/malicious-site-protection-impl/src/test/resources/reference_tests/canonicalization/canonicalization_tests.json
  package-lock.json
  package.json
Labels: reference tests, automated pr

#5839 Remove SinglePrintSafeguardFeature
  app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
  app/src/main/java/com/duckduckgo/app/browser/print/SinglePrintSafeguardFeature.kt
Labels: QA-Optional
